[workspace]
members = [
    "crates/aqua-components",
    "crates/aqua-compositor",
    "crates/aqua-host-tools",
    "crates/aqua-installer",
    "crates/aqua-renderer",
    "crates/aqua-scene",
    "crates/aqua-shell",
    "crates/aqua-text",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
rust-version = "1.85"
