#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
MANIFEST_JSON="${MANIFEST_JSON:-${ROOT_DIR}/build/aqua-image-manifest.json}"

if [ ! -f "${MANIFEST_JSON}" ]; then
    echo "Missing JSON image manifest: ${MANIFEST_JSON}" >&2
    echo "Run scripts/write-image-manifest.sh first." >&2
    exit 1
fi

python3 - "${MANIFEST_JSON}" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, "r", encoding="utf-8") as handle:
    manifest = json.load(handle)

expected = {
    ("product",): "Aqua Linux",
    ("base",): "Buildroot",
    ("dev_target",): "QEMU x86_64",
    ("graphics_target",): "custom Wayland compositor",
    ("artifacts", "rootfs_ext2", "status"): "ready",
    ("artifacts", "rootfs_tar", "status"): "ready",
    ("artifacts", "boot_summary", "status"): "ready",
    ("artifacts", "boot_summary_json", "status"): "ready",
    ("artifacts", "fbdev_qemu_present_log", "status"): "ready",
    ("artifacts", "graphical_boot_qemu_log", "status"): "ready",
    ("artifacts", "fbdev_qemu_capture", "status"): "ready",
    ("artifacts", "fbdev_qemu_ppm", "status"): "ready",
    ("artifacts", "fbdev_qemu_ppm", "bytes"): "3072016",
    ("artifacts", "fbdev_qemu_png", "status"): "ready",
    ("artifacts", "fbdev_qemu_sha256", "status"): "ready",
    ("artifacts", "kms_qemu_capture", "status"): "ready",
    ("artifacts", "kms_qemu_ppm", "status"): "ready",
    ("artifacts", "kms_qemu_ppm", "bytes"): "3072016",
    ("artifacts", "kms_qemu_png", "status"): "ready",
    ("artifacts", "kms_qemu_sha256", "status"): "ready",
    ("artifacts", "page_flip_qemu_capture", "status"): "ready",
    ("artifacts", "page_flip_qemu_ppm", "status"): "ready",
    ("artifacts", "page_flip_qemu_ppm", "bytes"): "3072016",
    ("artifacts", "page_flip_qemu_png", "status"): "ready",
    ("artifacts", "page_flip_qemu_sha256", "status"): "ready",
    ("artifacts", "frame_loop_qemu_capture", "status"): "ready",
    ("artifacts", "frame_loop_qemu_ppm", "status"): "ready",
    ("artifacts", "frame_loop_qemu_ppm", "bytes"): "3072016",
    ("artifacts", "frame_loop_qemu_png", "status"): "ready",
    ("artifacts", "frame_loop_qemu_sha256", "status"): "ready",
    ("artifacts", "session_loop_qemu_capture", "status"): "ready",
    ("artifacts", "session_loop_qemu_ppm", "status"): "ready",
    ("artifacts", "session_loop_qemu_ppm", "bytes"): "3072016",
    ("artifacts", "session_loop_qemu_png", "status"): "ready",
    ("artifacts", "session_loop_qemu_sha256", "status"): "ready",
    ("artifacts", "wayland_session_qemu_capture", "status"): "ready",
    ("artifacts", "wayland_session_qemu_ppm", "status"): "ready",
    ("artifacts", "wayland_session_qemu_ppm", "bytes"): "3072016",
    ("artifacts", "wayland_session_qemu_png", "status"): "ready",
    ("artifacts", "wayland_session_qemu_sha256", "status"): "ready",
    ("artifacts", "drm_device_probe", "status"): "ready",
    ("artifacts", "session_check_probe", "status"): "ready",
    ("artifacts", "manual_launch_plan", "status"): "ready",
    ("artifacts", "guarded_run", "status"): "ready",
    ("artifacts", "handoff_gate", "status"): "ready",
    ("artifacts", "output_plan_probe", "status"): "ready",
    ("artifacts", "display_output_handoff_probe", "status"): "ready",
    ("artifacts", "display_activation_plan_probe", "status"): "ready",
    ("artifacts", "display_output_smoke", "status"): "ready",
    ("artifacts", "nested_output_surface", "status"): "ready",
    ("artifacts", "visible_preview_plan_probe", "status"): "ready",
    ("artifacts", "visible_preview_export_probe", "status"): "ready",
    ("artifacts", "visible_preview_export", "status"): "ready",
    ("artifacts", "nested_preview_loop", "status"): "ready",
    ("artifacts", "manual_nested_preview_backend", "status"): "ready",
    ("artifacts", "manual_nested_preview_execution", "status"): "ready",
    ("artifacts", "manual_nested_preview_execution_probe", "status"): "ready",
    ("artifacts", "visible_preview_request", "status"): "ready",
    ("artifacts", "visible_preview_launch", "status"): "ready",
    ("artifacts", "recovery_help", "status"): "ready",
    ("artifacts", "operator_transcript", "status"): "ready",
    ("artifacts", "graphics_enable_gate", "status"): "ready",
    ("artifacts", "graphics_enable_gate_positive", "status"): "ready",
    ("artifacts", "graphics_launch_candidate", "status"): "ready",
    ("artifacts", "graphics_rollback_drill", "status"): "ready",
    ("artifacts", "graphics_startup_preflight", "status"): "ready",
    ("artifacts", "graphics_startup_rehearsal", "status"): "ready",
    ("artifacts", "graphics_qemu_display_gate", "status"): "ready",
    ("artifacts", "graphics_visible_qemu_attempt", "status"): "ready",
    ("artifacts", "graphics_visible_attempt_transcript", "status"): "ready",
    ("artifacts", "graphics_visible_attempt_result", "status"): "ready",
    ("artifacts", "graphics_visible_attempt_runner", "status"): "ready",
    ("artifacts", "graphics_qemu_visible_boot_check", "status"): "ready",
    ("artifacts", "graphics_fbdev_present", "status"): "ready",
    ("artifacts", "graphics_qemu_observation_marker", "status"): "ready",
    ("artifacts", "qemu_visible_evidence_record", "status"): "ready",
    ("artifacts", "graphics_qemu_observation_positive", "status"): "ready",
    ("artifacts", "qemu_visible_pass_report", "status"): "ready",
    ("artifacts", "qemu_visible_manual_runbook", "status"): "ready",
    ("artifacts", "qemu_visible_operator_pass", "status"): "ready",
    ("artifacts", "qemu_visible_operator_pass_json", "status"): "ready",
    ("artifacts", "qemu_visible_evidence_bundle_apply", "status"): "ready",
    ("artifacts", "qemu_visible_evidence_bundle_apply_positive", "status"): "ready",
    ("artifacts", "qemu_visible_evidence_bundle_apply_missing_preflight", "status"): "ready",
    ("artifacts", "client_window_model_probe", "status"): "ready",
    ("artifacts", "client_surface_lifecycle_probe", "status"): "ready",
    ("artifacts", "client_surface_registry_probe", "status"): "ready",
    ("artifacts", "xdg_shell_binding_probe", "status"): "ready",
    ("artifacts", "xdg_toplevel_client_probe", "status"): "ready",
    ("artifacts", "xdg_toplevel_window_model_probe", "status"): "ready",
    ("artifacts", "smithay_launcher_seat_probe", "status"): "ready",
    ("artifacts", "paint_plan_probe", "status"): "ready",
    ("artifacts", "frame_plan_probe", "status"): "ready",
    ("artifacts", "frame_buffer_probe", "status"): "ready",
    ("artifacts", "raster_probe", "status"): "ready",
    ("artifacts", "raster_export_probe", "status"): "ready",
    ("artifacts", "raster_export", "status"): "ready",
    ("artifacts", "raster_export", "bytes"): "4718609",
    ("artifacts", "raster_png_export_probe", "status"): "ready",
    ("artifacts", "raster_png_export", "status"): "ready",
    ("artifacts", "raster_png_export", "bytes"): "6293028",
    ("rootfs", "session_config_recovery_safe"): "ok",
    ("rootfs", "session_env_recovery_safe"): "ok",
    ("rootfs", "compositor_packaged"): "true",
    ("rootfs", "autostart"): False,
    ("rootfs", "boot_graphics"): False,
    ("artifacts", "graphical_session_supervisor", "status"): "ready",
    ("artifacts", "graphical_session_boot", "status"): "ready",
    ("scene_contract", "graphical_session_supervisor"): "ok",
    ("scene_contract", "graphical_session_supervisor_bounded"): "ok",
    ("scene_contract", "graphical_session_supervisor_recovery"): "ok",
    ("scene_contract", "graphical_session_supervisor_safe_default"): "ok",
    ("scene_contract", "graphical_session_boot"): "ok",
    ("scene_contract", "graphical_session_boot_kernel_gate"): "ok",
    ("scene_contract", "graphical_session_boot_safe_default"): "ok",
    ("scene_contract", "graphics_boot_qemu_persistent"): "ok",
    ("scene_contract", "graphics_boot_qemu_desktop_event_loop"): "ok",
    ("scene_contract", "graphics_boot_qemu_fixture_free"): "ok",
    ("scene_contract", "graphics_desktop_runtime_launch_qemu"): "ok",
    ("scene_contract", "graphics_desktop_runtime_launch_files"): "ok",
    ("scene_contract", "graphics_desktop_runtime_launch_repaint"): "ok",
    ("scene_contract", "graphics_desktop_runtime_settings"): "ok",
    ("scene_contract", "graphics_desktop_runtime_damage"): "ok",
    ("scene_contract", "graphics_desktop_runtime_close"): "ok",
    ("scene_contract", "graphics_desktop_runtime_unexpected_exit"): "ok",
    ("scene_contract", "graphics_desktop_runtime_cleanup"): "ok",
    ("scene_contract", "graphics_desktop_session_menu"): "ok",
    ("scene_contract", "graphics_desktop_session_menu_overlay"): "ok",
    ("scene_contract", "graphics_restart_qemu"): "ok",
    ("scene_contract", "graphics_session_cycle_qemu"): "ok",
    ("scene_contract", "graphics_session_cycle_qemu_sockets"): "ok",
    ("scene_contract", "graphics_session_cycle_qemu_pids"): "ok",
    ("scene_contract", "graphics_session_cycle_qemu_clients"): "ok",
    ("scene_contract", "graphics_session_cycle_qemu_drm"): "ok",
    ("scene_contract", "session_bootstrap_probe"): "ok",
    ("scene_contract", "session_check_probe"): "ok",
    ("scene_contract", "manual_launch_plan"): "ok",
    ("scene_contract", "renderer_gpu_runtime"): "ok",
    ("scene_contract", "renderer_gpu_backend_selected"): "ok",
    ("scene_contract", "renderer_gpu_software_fallback_safe"): "ok",
    ("scene_contract", "renderer_gpu_no_context"): "ok",
    ("scene_contract", "renderer_gpu_no_display_start"): "ok",
    ("scene_contract", "renderer_gpu_recovery_safe"): "ok",
    ("scene_contract", "renderer_gpu_offscreen_frame"): "ok",
    ("scene_contract", "renderer_gpu_context_created"): "ok",
    ("scene_contract", "renderer_gpu_frame_rendered"): "ok",
    ("scene_contract", "renderer_gpu_frame_synchronized"): "ok",
    ("scene_contract", "renderer_gpu_scene_surfaces"): "ok",
    ("scene_contract", "renderer_gpu_scene_surface_layers"): "ok",
    ("scene_contract", "renderer_gpu_scene_shader"): "ok",
    ("scene_contract", "renderer_gpu_surface_shader_compiled"): "ok",
    ("scene_contract", "renderer_gpu_surface_shader_panels"): "ok",
    ("scene_contract", "renderer_gpu_surface_refraction"): "ok",
    ("scene_contract", "renderer_gpu_surface_tint"): "ok",
    ("scene_contract", "renderer_gpu_surface_highlight"): "ok",
    ("scene_contract", "renderer_gpu_surface_bounded"): "ok",
    ("scene_contract", "renderer_gpu_surface_rounded_mask"): "ok",
    ("scene_contract", "renderer_gpu_surface_corner_radius"): "ok",
    ("scene_contract", "renderer_gpu_surface_edge_light"): "ok",
    ("scene_contract", "renderer_gpu_surface_edge_width"): "ok",
    ("scene_contract", "renderer_gpu_surface_blur_shader"): "ok",
    ("scene_contract", "renderer_gpu_surface_blur_passes"): "ok",
    ("scene_contract", "renderer_gpu_surface_blur_kernel"): "ok",
    ("scene_contract", "renderer_gpu_surface_blur_radius"): "ok",
    ("scene_contract", "renderer_gpu_surface_blur_intermediate"): "ok",
    ("scene_contract", "renderer_gpu_surface_blur_synchronized"): "ok",
    ("scene_contract", "renderer_gpu_surface_blur_composited"): "ok",
    ("scene_contract", "renderer_gpu_wallpaper_runtime"): "ok",
    ("scene_contract", "renderer_gpu_wallpaper_size"): "ok",
    ("scene_contract", "renderer_gpu_wallpaper_uploaded"): "ok",
    ("scene_contract", "renderer_gpu_wallpaper_composited"): "ok",
    ("scene_contract", "renderer_gpu_client_texture_source"): "ok",
    ("scene_contract", "renderer_gpu_client_texture_count"): "ok",
    ("scene_contract", "renderer_gpu_client_texture_bytes"): "ok",
    ("scene_contract", "renderer_gpu_client_textures_uploaded"): "ok",
    ("scene_contract", "renderer_gpu_client_textures_composited"): "ok",
    ("scene_contract", "renderer_gpu_client_not_live"): "ok",
    ("scene_contract", "renderer_gpu_frame_readback"): "ok",
    ("scene_contract", "renderer_gpu_frame_bytes"): "ok",
    ("scene_contract", "renderer_gpu_frame_checksum"): "ok",
    ("scene_contract", "renderer_gpu_frame_deterministic"): "ok",
    ("scene_contract", "renderer_gpu_context_destroyed"): "ok",
    ("scene_contract", "renderer_gpu_offscreen_no_kms"): "ok",
    ("scene_contract", "renderer_gpu_offscreen_no_display"): "ok",
    ("scene_contract", "renderer_gpu_offscreen_recovery_safe"): "ok",
    ("scene_contract", "manual_launch_safe"): "ok",
    ("scene_contract", "manual_launch_no_autostart"): "ok",
    ("scene_contract", "manual_launch_no_boot_graphics"): "ok",
    ("scene_contract", "manual_launch_recovery_tty"): "ok",
    ("scene_contract", "manual_launch_no_display_start"): "ok",
    ("scene_contract", "manual_launch_no_shell_start"): "ok",
    ("scene_contract", "guarded_run"): "ok",
    ("scene_contract", "guarded_run_complete"): "ok",
    ("scene_contract", "guarded_run_launch_plan"): "ok",
    ("scene_contract", "guarded_run_bounded"): "ok",
    ("scene_contract", "guarded_run_frames"): "ok",
    ("scene_contract", "guarded_run_started"): "ok",
    ("scene_contract", "guarded_run_stopped"): "ok",
    ("scene_contract", "guarded_run_fallback_tty"): "ok",
    ("scene_contract", "guarded_run_no_autostart"): "ok",
    ("scene_contract", "guarded_run_no_boot_graphics"): "ok",
    ("scene_contract", "guarded_run_no_shell"): "ok",
    ("scene_contract", "guarded_run_return"): "ok",
    ("scene_contract", "handoff_gate"): "ok",
    ("scene_contract", "handoff_gate_ready"): "ok",
    ("scene_contract", "handoff_gate_guarded"): "ok",
    ("scene_contract", "handoff_gate_handoff"): "ok",
    ("scene_contract", "handoff_gate_preview"): "ok",
    ("scene_contract", "handoff_gate_loop"): "ok",
    ("scene_contract", "handoff_gate_backend"): "ok",
    ("scene_contract", "handoff_gate_backend_ready"): "ok",
    ("scene_contract", "handoff_gate_backend_no_start"): "ok",
    ("scene_contract", "handoff_gate_candidate"): "ok",
    ("scene_contract", "handoff_gate_manual"): "ok",
    ("scene_contract", "handoff_gate_no_auto"): "ok",
    ("scene_contract", "handoff_gate_recovery"): "ok",
    ("scene_contract", "output_plan"): "ok",
    ("scene_contract", "output_plan_backend"): "ok",
    ("scene_contract", "output_plan_later_backend"): "ok",
    ("scene_contract", "output_plan_recovery_safe"): "ok",
    ("scene_contract", "display_output_handoff"): "ok",
    ("scene_contract", "display_output_handoff_ready"): "ok",
    ("scene_contract", "display_output_handoff_backend"): "ok",
    ("scene_contract", "display_output_handoff_framebuffer"): "ok",
    ("scene_contract", "display_output_handoff_frame_format"): "ok",
    ("scene_contract", "display_output_handoff_frame_checksum"): "ok",
    ("scene_contract", "display_output_handoff_client_snapshot"): "ok",
    ("scene_contract", "display_output_handoff_snapshot_mode"): "ok",
    ("scene_contract", "display_output_handoff_no_start"): "ok",
    ("scene_contract", "display_output_handoff_recovery_safe"): "ok",
    ("scene_contract", "display_activation_plan"): "ok",
    ("scene_contract", "display_activation_plan_ready"): "ok",
    ("scene_contract", "display_activation_plan_manual"): "ok",
    ("scene_contract", "display_activation_plan_handoff"): "ok",
    ("scene_contract", "display_activation_plan_frame"): "ok",
    ("scene_contract", "display_activation_plan_fallback_tty"): "ok",
    ("scene_contract", "display_activation_plan_can_activate"): "ok",
    ("scene_contract", "display_activation_plan_no_start"): "ok",
    ("scene_contract", "display_activation_plan_no_autostart"): "ok",
    ("scene_contract", "display_activation_plan_recovery_safe"): "ok",
    ("scene_contract", "display_output_smoke"): "ok",
    ("scene_contract", "display_output_smoke_complete"): "ok",
    ("scene_contract", "display_output_smoke_started"): "ok",
    ("scene_contract", "display_output_smoke_stopped"): "ok",
    ("scene_contract", "display_output_smoke_frames"): "ok",
    ("scene_contract", "display_output_smoke_no_autostart"): "ok",
    ("scene_contract", "display_output_smoke_no_boot_graphics"): "ok",
    ("scene_contract", "display_output_smoke_recovery_safe"): "ok",
    ("scene_contract", "nested_output_surface"): "ok",
    ("scene_contract", "nested_output_surface_complete"): "ok",
    ("scene_contract", "nested_output_surface_acquired"): "ok",
    ("scene_contract", "nested_output_surface_configured"): "ok",
    ("scene_contract", "nested_output_surface_frame_attached"): "ok",
    ("scene_contract", "nested_output_surface_frame_presented"): "ok",
    ("scene_contract", "nested_output_surface_released"): "ok",
    ("scene_contract", "nested_output_surface_frames"): "ok",
    ("scene_contract", "nested_output_surface_no_autostart"): "ok",
    ("scene_contract", "nested_output_surface_no_boot_graphics"): "ok",
    ("scene_contract", "nested_output_surface_recovery_safe"): "ok",
    ("scene_contract", "manual_nested_preview_backend"): "ok",
    ("scene_contract", "manual_nested_preview_backend_ready"): "ok",
    ("scene_contract", "manual_nested_preview_backend_path"): "ok",
    ("scene_contract", "manual_nested_preview_backend_selected"): "ok",
    ("scene_contract", "manual_nested_preview_backend_handoff"): "ok",
    ("scene_contract", "manual_nested_preview_backend_surface"): "ok",
    ("scene_contract", "manual_nested_preview_backend_loop"): "ok",
    ("scene_contract", "manual_nested_preview_backend_export"): "ok",
    ("scene_contract", "manual_nested_preview_backend_frame"): "ok",
    ("scene_contract", "manual_nested_preview_backend_checksum_match"): "ok",
    ("scene_contract", "manual_nested_preview_backend_fallback_tty"): "ok",
    ("scene_contract", "manual_nested_preview_backend_no_start"): "ok",
    ("scene_contract", "manual_nested_preview_backend_stopped"): "ok",
    ("scene_contract", "manual_nested_preview_backend_no_autostart"): "ok",
    ("scene_contract", "manual_nested_preview_backend_recovery_safe"): "ok",
    ("scene_contract", "manual_nested_preview_execution"): "ok",
    ("scene_contract", "manual_nested_preview_execution_ready"): "ok",
    ("scene_contract", "manual_nested_preview_execution_gate"): "ok",
    ("scene_contract", "manual_nested_preview_execution_backend"): "ok",
    ("scene_contract", "manual_nested_preview_execution_operator"): "ok",
    ("scene_contract", "manual_nested_preview_execution_frames"): "ok",
    ("scene_contract", "manual_nested_preview_execution_started"): "ok",
    ("scene_contract", "manual_nested_preview_execution_stopped"): "ok",
    ("scene_contract", "manual_nested_preview_execution_cleanup"): "ok",
    ("scene_contract", "manual_nested_preview_execution_return"): "ok",
    ("scene_contract", "manual_nested_preview_execution_no_autostart"): "ok",
    ("scene_contract", "manual_nested_preview_execution_no_boot_graphics"): "ok",
    ("scene_contract", "manual_nested_preview_execution_probe"): "ok",
    ("scene_contract", "manual_nested_preview_execution_probe_complete"): "ok",
    ("scene_contract", "visible_preview_request"): "ok",
    ("scene_contract", "visible_preview_request_ready"): "ok",
    ("scene_contract", "visible_preview_request_target"): "ok",
    ("scene_contract", "visible_preview_request_backend"): "ok",
    ("scene_contract", "visible_preview_request_feature_gate"): "ok",
    ("scene_contract", "visible_preview_request_manual_execution"): "ok",
    ("scene_contract", "visible_preview_request_file"): "ok",
    ("scene_contract", "visible_preview_request_host_tool_not_packaged"): "ok",
    ("scene_contract", "visible_preview_request_no_autostart"): "ok",
    ("scene_contract", "visible_preview_request_no_boot_graphics"): "ok",
    ("scene_contract", "visible_preview_request_recovery_safe"): "ok",
    ("scene_contract", "visible_preview_launch"): "ok",
    ("scene_contract", "visible_preview_launch_ready"): "ok",
    ("scene_contract", "visible_preview_launch_request"): "ok",
    ("scene_contract", "visible_preview_launch_plan"): "ok",
    ("scene_contract", "visible_preview_launch_backend"): "ok",
    ("scene_contract", "visible_preview_launch_feature_gate"): "ok",
    ("scene_contract", "visible_preview_launch_host_tool_not_packaged"): "ok",
    ("scene_contract", "visible_preview_launch_no_qemu_window"): "ok",
    ("scene_contract", "visible_preview_launch_no_preview_window"): "ok",
    ("scene_contract", "visible_preview_launch_no_autostart"): "ok",
    ("scene_contract", "visible_preview_launch_no_boot_graphics"): "ok",
    ("scene_contract", "visible_preview_launch_recovery_safe"): "ok",
    ("scene_contract", "recovery_help"): "ok",
    ("scene_contract", "recovery_help_text_mode"): "ok",
    ("scene_contract", "recovery_help_no_autostart"): "ok",
    ("scene_contract", "recovery_help_no_boot_graphics"): "ok",
    ("scene_contract", "recovery_help_visible_launcher"): "ok",
    ("scene_contract", "recovery_help_host_tool_external"): "ok",
    ("scene_contract", "recovery_help_operator_pass_host"): "ok",
    ("scene_contract", "recovery_help_operator_pass_no_launch"): "ok",
    ("scene_contract", "recovery_help_operator_checklist"): "ok",
    ("scene_contract", "recovery_help_operator_pass_artifact"): "ok",
    ("scene_contract", "recovery_help_operator_pass_external"): "ok",
    ("scene_contract", "recovery_help_visible_pass_report"): "ok",
    ("scene_contract", "recovery_help_pass_report_required"): "ok",
    ("scene_contract", "recovery_help_pass_report_after_apply"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_no_launch"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_launch_required"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_not_confirmed"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_no_positive_without_evidence"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_no_unverified_bundle"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_recovery_safe"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_stop_rule"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_no_launch_command"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_confirmed_command"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_capture_flow"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_capture_verify"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_evidence_flow"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_vm_apply"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_capture_hash_gate"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_capture_hash_status"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_positive_capture_hash_status"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_missing_capture_hash_rejected"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_manual_runbook_pass_report_required"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_preflight_source"): "ok",
    ("scene_contract", "qemu_visible_operator_pass_preflight_mtime"): "ok",
    ("scene_contract", "operator_transcript"): "ok",
    ("scene_contract", "operator_transcript_ready"): "ok",
    ("scene_contract", "operator_transcript_dry_run"): "ok",
    ("scene_contract", "operator_transcript_qemu_steps"): "ok",
    ("scene_contract", "operator_transcript_host_steps"): "ok",
    ("scene_contract", "operator_transcript_qemu_command"): "ok",
    ("scene_contract", "operator_transcript_host_command"): "ok",
    ("scene_contract", "operator_transcript_host_tool_not_packaged"): "ok",
    ("scene_contract", "operator_transcript_no_autostart"): "ok",
    ("scene_contract", "operator_transcript_no_boot_graphics"): "ok",
    ("scene_contract", "operator_transcript_recovery_safe"): "ok",
    ("scene_contract", "graphics_enable_gate"): "ok",
    ("scene_contract", "graphics_enable_gate_ready"): "ok",
    ("scene_contract", "graphics_enable_gate_preflight"): "ok",
    ("scene_contract", "graphics_enable_gate_allow_handoff"): "ok",
    ("scene_contract", "graphics_enable_gate_allow_manual_execution"): "ok",
    ("scene_contract", "graphics_enable_gate_allow_fallback_tty"): "ok",
    ("scene_contract", "graphics_enable_gate_allow_boot_graphics"): "ok",
    ("scene_contract", "graphics_enable_gate_check_handoff"): "ok",
    ("scene_contract", "graphics_enable_gate_check_manual_execution"): "ok",
    ("scene_contract", "graphics_enable_gate_check_fallback_tty"): "ok",
    ("scene_contract", "graphics_enable_gate_check_cleanup"): "ok",
    ("scene_contract", "graphics_enable_gate_check_stopped"): "ok",
    ("scene_contract", "graphics_enable_gate_currently_blocked"): "ok",
    ("scene_contract", "graphics_enable_gate_refused"): "ok",
    ("scene_contract", "graphics_enable_gate_reason"): "ok",
    ("scene_contract", "graphics_enable_gate_blocked_criteria"): "ok",
    ("scene_contract", "graphics_enable_gate_plan"): "ok",
    ("scene_contract", "graphics_enable_gate_no_autostart"): "ok",
    ("scene_contract", "graphics_enable_gate_no_boot_graphics"): "ok",
    ("scene_contract", "graphics_enable_gate_no_display_start"): "ok",
    ("scene_contract", "graphics_enable_gate_recovery_safe"): "ok",
    ("scene_contract", "graphics_enable_gate_positive"): "ok",
    ("scene_contract", "graphics_enable_gate_positive_preflight"): "ok",
    ("scene_contract", "graphics_enable_gate_positive_dry_run"): "ok",
    ("scene_contract", "graphics_enable_gate_positive_handoff"): "ok",
    ("scene_contract", "graphics_enable_gate_positive_manual_execution"): "ok",
    ("scene_contract", "graphics_enable_gate_positive_allowable"): "ok",
    ("scene_contract", "graphics_enable_gate_positive_decision"): "ok",
    ("scene_contract", "graphics_enable_gate_positive_no_actual_start"): "ok",
    ("scene_contract", "graphics_enable_gate_positive_no_boot_graphics"): "ok",
    ("scene_contract", "graphics_enable_gate_positive_recovery_safe"): "ok",
    ("scene_contract", "graphics_launch_candidate"): "ok",
    ("scene_contract", "graphics_launch_candidate_ready"): "ok",
    ("scene_contract", "graphics_launch_candidate_allowable"): "ok",
    ("scene_contract", "graphics_launch_candidate_selected"): "ok",
    ("scene_contract", "graphics_launch_candidate_not_started"): "ok",
    ("scene_contract", "graphics_launch_candidate_no_actual_start"): "ok",
    ("scene_contract", "graphics_launch_candidate_no_display_start"): "ok",
    ("scene_contract", "graphics_launch_candidate_rollback"): "ok",
    ("scene_contract", "graphics_launch_candidate_recovery_safe"): "ok",
    ("scene_contract", "graphics_rollback_drill"): "ok",
    ("scene_contract", "graphics_rollback_drill_ready"): "ok",
    ("scene_contract", "graphics_rollback_drill_cancel_path"): "ok",
    ("scene_contract", "graphics_rollback_drill_failure_path"): "ok",
    ("scene_contract", "graphics_rollback_drill_not_started"): "ok",
    ("scene_contract", "graphics_rollback_drill_no_actual_start"): "ok",
    ("scene_contract", "graphics_rollback_drill_no_display_start"): "ok",
    ("scene_contract", "graphics_rollback_drill_verified"): "ok",
    ("scene_contract", "graphics_rollback_drill_command"): "ok",
    ("scene_contract", "graphics_rollback_drill_recovery_safe"): "ok",
    ("scene_contract", "graphics_startup_preflight"): "ok",
    ("scene_contract", "graphics_startup_preflight_ready"): "ok",
    ("scene_contract", "graphics_startup_preflight_bounded"): "ok",
    ("scene_contract", "graphics_startup_preflight_operator_ack"): "ok",
    ("scene_contract", "graphics_startup_preflight_fallback_tty"): "ok",
    ("scene_contract", "graphics_startup_preflight_rollback"): "ok",
    ("scene_contract", "graphics_startup_preflight_decision"): "ok",
    ("scene_contract", "graphics_startup_preflight_not_started"): "ok",
    ("scene_contract", "graphics_startup_preflight_no_actual_start"): "ok",
    ("scene_contract", "graphics_startup_preflight_no_display_start"): "ok",
    ("scene_contract", "graphics_startup_preflight_recovery_safe"): "ok",
    ("scene_contract", "graphics_startup_rehearsal"): "ok",
    ("scene_contract", "graphics_startup_rehearsal_ready"): "ok",
    ("scene_contract", "graphics_startup_rehearsal_bounded"): "ok",
    ("scene_contract", "graphics_startup_rehearsal_frames"): "ok",
    ("scene_contract", "graphics_startup_rehearsal_started"): "ok",
    ("scene_contract", "graphics_startup_rehearsal_stopped"): "ok",
    ("scene_contract", "graphics_startup_rehearsal_no_actual_graphics"): "ok",
    ("scene_contract", "graphics_startup_rehearsal_no_desktop_shell"): "ok",
    ("scene_contract", "graphics_startup_rehearsal_decision"): "ok",
    ("scene_contract", "graphics_startup_rehearsal_recovery_safe"): "ok",
    ("scene_contract", "graphics_qemu_display_gate"): "ok",
    ("scene_contract", "graphics_qemu_display_gate_ready"): "ok",
    ("scene_contract", "graphics_qemu_display_gate_candidate"): "ok",
    ("scene_contract", "graphics_qemu_display_gate_passed"): "ok",
    ("scene_contract", "graphics_qemu_display_gate_decision"): "ok",
    ("scene_contract", "graphics_qemu_display_gate_manual"): "ok",
    ("scene_contract", "graphics_qemu_display_gate_not_started"): "ok",
    ("scene_contract", "graphics_qemu_display_gate_no_actual_graphics"): "ok",
    ("scene_contract", "graphics_qemu_display_gate_no_desktop_shell"): "ok",
    ("scene_contract", "graphics_qemu_display_gate_recovery_safe"): "ok",
    ("scene_contract", "graphics_visible_qemu_attempt"): "ok",
    ("scene_contract", "graphics_visible_qemu_attempt_ready"): "ok",
    ("scene_contract", "graphics_visible_qemu_attempt_plan"): "ok",
    ("scene_contract", "graphics_visible_qemu_attempt_allowed"): "ok",
    ("scene_contract", "graphics_visible_qemu_attempt_not_started"): "ok",
    ("scene_contract", "graphics_visible_qemu_attempt_manual"): "ok",
    ("scene_contract", "graphics_visible_qemu_attempt_fallback_tty"): "ok",
    ("scene_contract", "graphics_visible_qemu_attempt_no_desktop_shell"): "ok",
    ("scene_contract", "graphics_visible_qemu_attempt_command"): "ok",
    ("scene_contract", "graphics_visible_qemu_attempt_recovery_safe"): "ok",
    ("scene_contract", "graphics_visible_attempt_transcript"): "ok",
    ("scene_contract", "graphics_visible_attempt_transcript_ready"): "ok",
    ("scene_contract", "graphics_visible_attempt_transcript_sequence"): "ok",
    ("scene_contract", "graphics_visible_attempt_transcript_step_attempt"): "ok",
    ("scene_contract", "graphics_visible_attempt_transcript_step_run"): "ok",
    ("scene_contract", "graphics_visible_attempt_transcript_expected_return"): "ok",
    ("scene_contract", "graphics_visible_attempt_transcript_not_started"): "ok",
    ("scene_contract", "graphics_visible_attempt_transcript_no_persistent"): "ok",
    ("scene_contract", "graphics_visible_attempt_transcript_no_desktop_shell"): "ok",
    ("scene_contract", "graphics_visible_attempt_transcript_recovery_safe"): "ok",
    ("scene_contract", "graphics_visible_attempt_result"): "ok",
    ("scene_contract", "graphics_visible_attempt_result_ready"): "ok",
    ("scene_contract", "graphics_visible_attempt_result_source"): "ok",
    ("scene_contract", "graphics_visible_attempt_result_manual_not_run"): "ok",
    ("scene_contract", "graphics_visible_attempt_result_collected"): "ok",
    ("scene_contract", "graphics_visible_attempt_result_not_started"): "ok",
    ("scene_contract", "graphics_visible_attempt_result_not_completed"): "ok",
    ("scene_contract", "graphics_visible_attempt_result_no_display_start"): "ok",
    ("scene_contract", "graphics_visible_attempt_result_no_display_stop"): "ok",
    ("scene_contract", "graphics_visible_attempt_result_no_persistent"): "ok",
    ("scene_contract", "graphics_visible_attempt_result_no_desktop_shell"): "ok",
    ("scene_contract", "graphics_visible_attempt_result_no_boot_graphics"): "ok",
    ("scene_contract", "graphics_visible_attempt_result_no_autostart"): "ok",
    ("scene_contract", "graphics_visible_attempt_result_recovery_safe"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_ready"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_guarded"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_bounded"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_result"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_collector"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_started"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_completed"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_frames"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_display_started"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_display_stopped"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_no_persistent"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_no_desktop_shell"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_no_boot_graphics"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_no_autostart"): "ok",
    ("scene_contract", "graphics_visible_attempt_runner_recovery_safe"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_check"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_check_ready"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_check_runner"): "ok",
    ("scene_contract", "graphics_fbdev_present"): "ok",
    ("scene_contract", "graphics_fbdev_present_probe"): "ok",
    ("scene_contract", "graphics_fbdev_present_frame"): "ok",
    ("scene_contract", "graphics_fbdev_present_not_started"): "ok",
    ("scene_contract", "graphics_fbdev_present_bounded"): "ok",
    ("scene_contract", "graphics_fbdev_present_no_boot_graphics"): "ok",
    ("scene_contract", "graphics_fbdev_present_no_autostart"): "ok",
    ("scene_contract", "graphics_fbdev_present_recovery_safe"): "ok",
    ("scene_contract", "graphics_fbdev_headless_qemu_write"): "ok",
    ("scene_contract", "graphics_fbdev_headless_qemu_checksum"): "ok",
    ("scene_contract", "graphics_fbdev_headless_qemu_wallpaper"): "ok",
    ("scene_contract", "graphics_fbdev_headless_qemu_mode"): "ok",
    ("scene_contract", "graphics_fbdev_headless_qemu_recovery_safe"): "ok",
    ("scene_contract", "graphics_fbdev_headless_qemu_capture"): "ok",
    ("scene_contract", "graphics_fbdev_headless_qemu_capture_dimensions"): "ok",
    ("scene_contract", "graphics_fbdev_headless_qemu_ppm_checksum"): "ok",
    ("scene_contract", "graphics_fbdev_headless_qemu_png_checksum"): "ok",
    ("scene_contract", "graphics_fbdev_headless_qemu_capture_unobserved"): "ok",
    ("scene_contract", "graphics_drm_rootfs_probe"): "ok",
    ("scene_contract", "graphics_drm_qemu_probe"): "ok",
    ("scene_contract", "graphics_drm_qemu_device"): "ok",
    ("scene_contract", "graphics_drm_qemu_connector"): "ok",
    ("scene_contract", "graphics_drm_qemu_mode"): "ok",
    ("scene_contract", "graphics_drm_read_only"): "ok",
    ("scene_contract", "graphics_drm_no_master"): "ok",
    ("scene_contract", "graphics_drm_no_modeset"): "ok",
    ("scene_contract", "graphics_drm_dumb_buffer"): "ok",
    ("scene_contract", "graphics_drm_dumb_buffer_mode"): "ok",
    ("scene_contract", "graphics_drm_dumb_buffer_pitch"): "ok",
    ("scene_contract", "graphics_drm_dumb_buffer_bytes"): "ok",
    ("scene_contract", "graphics_drm_dumb_buffer_checksum"): "ok",
    ("scene_contract", "graphics_drm_dumb_buffer_mapped"): "ok",
    ("scene_contract", "graphics_drm_dumb_buffer_destroyed"): "ok",
    ("scene_contract", "graphics_drm_dumb_buffer_no_framebuffer"): "ok",
    ("scene_contract", "graphics_drm_dumb_buffer_no_page_flip"): "ok",
    ("scene_contract", "graphics_drm_dumb_buffer_recovery_safe"): "ok",
    ("scene_contract", "graphics_drm_gbm_scanout_buffer"): "ok",
    ("scene_contract", "graphics_drm_gbm_scanout_usage"): "ok",
    ("scene_contract", "graphics_drm_gbm_scanout_pitch"): "ok",
    ("scene_contract", "graphics_drm_gbm_dmabuf_export"): "ok",
    ("scene_contract", "graphics_drm_gbm_addfb2"): "ok",
    ("scene_contract", "graphics_drm_gbm_framebuffer_cleanup"): "ok",
    ("scene_contract", "graphics_drm_gbm_direct_scanout"): "ok",
    ("scene_contract", "graphics_drm_gbm_direct_rendered"): "ok",
    ("scene_contract", "graphics_drm_gbm_direct_no_cpu_copy"): "ok",
    ("scene_contract", "graphics_drm_gbm_direct_page_flip"): "ok",
    ("scene_contract", "graphics_drm_gbm_direct_crtc_restored"): "ok",
    ("scene_contract", "graphics_drm_gbm_direct_capture"): "ok",
    ("scene_contract", "graphics_drm_gbm_direct_capture_dimensions"): "ok",
    ("scene_contract", "graphics_drm_gbm_direct_ppm_checksum"): "ok",
    ("scene_contract", "graphics_drm_gbm_direct_png_checksum"): "ok",
    ("scene_contract", "graphics_drm_kms_present"): "ok",
    ("scene_contract", "graphics_drm_kms_active"): "ok",
    ("scene_contract", "graphics_drm_kms_framebuffer"): "ok",
    ("scene_contract", "graphics_drm_kms_activated"): "ok",
    ("scene_contract", "graphics_drm_kms_no_page_flip"): "ok",
    ("scene_contract", "graphics_drm_kms_crtc_restored"): "ok",
    ("scene_contract", "graphics_drm_kms_framebuffer_destroyed"): "ok",
    ("scene_contract", "graphics_drm_kms_recovery_safe"): "ok",
    ("scene_contract", "graphics_drm_kms_capture"): "ok",
    ("scene_contract", "graphics_drm_kms_capture_dimensions"): "ok",
    ("scene_contract", "graphics_drm_kms_ppm_checksum"): "ok",
    ("scene_contract", "graphics_drm_kms_png_checksum"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_active"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_composition"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_shader"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_blur"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_page_flip"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_bridge"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_no_direct_scanout"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_client_source"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_client_count"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_client_composited"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_client_not_live"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_capture"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_capture_dimensions"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_ppm_checksum"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_png_checksum"): "ok",
    ("scene_contract", "graphics_drm_gpu_surface_crtc_restored"): "ok",
    ("scene_contract", "graphics_drm_page_flip"): "ok",
    ("scene_contract", "graphics_drm_page_flip_active"): "ok",
    ("scene_contract", "graphics_drm_page_flip_submitted"): "ok",
    ("scene_contract", "graphics_drm_page_flip_event"): "ok",
    ("scene_contract", "graphics_drm_page_flip_front_destroyed"): "ok",
    ("scene_contract", "graphics_drm_page_flip_back_destroyed"): "ok",
    ("scene_contract", "graphics_drm_page_flip_crtc_restored"): "ok",
    ("scene_contract", "graphics_drm_page_flip_recovery_safe"): "ok",
    ("scene_contract", "graphics_drm_page_flip_capture"): "ok",
    ("scene_contract", "graphics_drm_page_flip_capture_dimensions"): "ok",
    ("scene_contract", "graphics_drm_page_flip_ppm_checksum"): "ok",
    ("scene_contract", "graphics_drm_page_flip_png_checksum"): "ok",
    ("scene_contract", "graphics_drm_frame_loop"): "ok",
    ("scene_contract", "graphics_drm_frame_loop_active"): "ok",
    ("scene_contract", "graphics_drm_frame_loop_submitted"): "ok",
    ("scene_contract", "graphics_drm_frame_loop_received"): "ok",
    ("scene_contract", "graphics_drm_frame_loop_order"): "ok",
    ("scene_contract", "graphics_drm_frame_loop_alternation"): "ok",
    ("scene_contract", "graphics_drm_frame_loop_crtc_restored"): "ok",
    ("scene_contract", "graphics_drm_frame_loop_recovery_safe"): "ok",
    ("scene_contract", "graphics_drm_frame_loop_capture"): "ok",
    ("scene_contract", "graphics_drm_frame_loop_capture_dimensions"): "ok",
    ("scene_contract", "graphics_drm_frame_loop_ppm_checksum"): "ok",
    ("scene_contract", "graphics_drm_frame_loop_png_checksum"): "ok",
    ("scene_contract", "graphics_drm_session_loop"): "ok",
    ("scene_contract", "graphics_drm_session_loop_active"): "ok",
    ("scene_contract", "graphics_drm_session_loop_owner"): "ok",
    ("scene_contract", "graphics_drm_session_loop_calloop"): "ok",
    ("scene_contract", "graphics_drm_session_loop_source_owned"): "ok",
    ("scene_contract", "graphics_drm_session_loop_dispatch"): "ok",
    ("scene_contract", "graphics_drm_session_loop_source_released"): "ok",
    ("scene_contract", "graphics_drm_session_loop_wayland_stopped"): "ok",
    ("scene_contract", "graphics_drm_session_loop_recovery_safe"): "ok",
    ("scene_contract", "graphics_drm_session_loop_capture"): "ok",
    ("scene_contract", "graphics_drm_session_loop_capture_dimensions"): "ok",
    ("scene_contract", "graphics_drm_session_loop_ppm_checksum"): "ok",
    ("scene_contract", "graphics_drm_session_loop_png_checksum"): "ok",
    ("scene_contract", "graphics_drm_wayland_session"): "ok",
    ("scene_contract", "graphics_drm_wayland_session_active"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_composition"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_render_node"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_same_kms_node"): "ok",
    ("scene_contract", "graphics_drm_wayland_direct_scanout"): "ok",
    ("scene_contract", "graphics_drm_wayland_no_cpu_scanout_copy"): "ok",
    ("scene_contract", "graphics_drm_wayland_gbm_cleanup"): "ok",
    ("scene_contract", "graphics_drm_wayland_no_frame_readback"): "ok",
    ("scene_contract", "graphics_drm_wayland_input_checksum"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_live_source"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_live_count"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_live_bytes"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_live_uploaded"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_live_composited"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_live_session"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_initial_frame"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_session_context"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_repaint"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_context_reused"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_repaint_source_order"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_repaint_count"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_repaint_bytes"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_repaint_checksum"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_files_repaint"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_settings_repaint"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_cleanup_repaint"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_close_repaint"): "ok",
    ("scene_contract", "graphics_drm_wayland_gpu_full_repaint_route"): "ok",
    ("scene_contract", "graphics_drm_wayland_shared_lifecycle"): "ok",
    ("scene_contract", "graphics_drm_wayland_display"): "ok",
    ("scene_contract", "graphics_drm_wayland_socket"): "ok",
    ("scene_contract", "graphics_drm_wayland_client"): "ok",
    ("scene_contract", "graphics_drm_wayland_dispatch"): "ok",
    ("scene_contract", "graphics_drm_wayland_flush"): "ok",
    ("scene_contract", "graphics_drm_wayland_drm_dispatch"): "ok",
    ("scene_contract", "graphics_drm_wayland_smithay_globals"): "ok",
    ("scene_contract", "graphics_drm_wayland_compositor_global"): "ok",
    ("scene_contract", "graphics_drm_wayland_shm_global"): "ok",
    ("scene_contract", "graphics_drm_wayland_xdg_shell_global"): "ok",
    ("scene_contract", "graphics_drm_wayland_seat"): "ok",
    ("scene_contract", "graphics_drm_wayland_socket_cleaned"): "ok",
    ("scene_contract", "graphics_drm_wayland_recovery_safe"): "ok",
    ("scene_contract", "graphics_drm_wayland_input_source"): "ok",
    ("scene_contract", "graphics_drm_wayland_input_discovery"): "ok",
    ("scene_contract", "graphics_drm_wayland_input_keyboard"): "ok",
    ("scene_contract", "graphics_drm_wayland_input_selective_forward"): "ok",
    ("scene_contract", "graphics_drm_wayland_input_pointer_hit_test"): "ok",
    ("scene_contract", "graphics_drm_wayland_input_pointer_motion"): "ok",
    ("scene_contract", "graphics_drm_wayland_input_pointer_button"): "ok",
    ("scene_contract", "graphics_drm_wayland_input_launcher"): "ok",
    ("scene_contract", "graphics_drm_wayland_launcher_overlay"): "ok",
    ("scene_contract", "graphics_drm_wayland_launcher_pointer"): "ok",
    ("scene_contract", "graphics_drm_wayland_launcher_preflight"): "ok",
    ("scene_contract", "graphics_drm_wayland_launcher_process"): "ok",
    ("scene_contract", "graphics_drm_wayland_process_supervisor"): "ok",
    ("scene_contract", "graphics_session_supervisor_qemu"): "ok",
    ("scene_contract", "graphics_session_supervisor_qemu_failures"): "ok",
    ("scene_contract", "graphics_session_supervisor_qemu_restarts"): "ok",
    ("scene_contract", "graphics_session_supervisor_qemu_recovery"): "ok",
    ("scene_contract", "graphics_boot_qemu"): "ok",
    ("scene_contract", "graphics_boot_qemu_activation"): "ok",
    ("scene_contract", "graphics_boot_qemu_wayland"): "ok",
    ("scene_contract", "graphics_boot_qemu_recovery_tty"): "ok",
    ("scene_contract", "graphics_stop_qemu"): "ok",
    ("scene_contract", "graphics_stop_qemu_clients"): "ok",
    ("scene_contract", "graphics_stop_qemu_kms"): "ok",
    ("scene_contract", "graphics_stop_qemu_gbm"): "ok",
    ("scene_contract", "graphics_stop_qemu_pid"): "ok",
    ("scene_contract", "graphics_stop_qemu_recovery"): "ok",
    ("scene_contract", "graphics_drm_wayland_settings"): "ok",
    ("scene_contract", "graphics_drm_wayland_settings_interaction"): "ok",
    ("scene_contract", "graphics_drm_wayland_settings_persistence"): "ok",
    ("scene_contract", "graphics_drm_wayland_settings_desktop"): "ok",
    ("scene_contract", "graphics_drm_wayland_settings_input"): "ok",
    ("scene_contract", "graphics_drm_wayland_settings_network"): "ok",
    ("scene_contract", "graphics_drm_wayland_real_font"): "ok",
    ("scene_contract", "graphics_drm_wayland_launcher_surface_owner"): "ok",
    ("scene_contract", "graphics_drm_wayland_files_window"): "ok",
    ("scene_contract", "graphics_drm_wayland_files_read_only"): "ok",
    ("scene_contract", "graphics_drm_wayland_files_pointer"): "ok",
    ("scene_contract", "graphics_drm_wayland_files_navigation"): "ok",
    ("scene_contract", "graphics_drm_wayland_files_keyboard"): "ok",
    ("scene_contract", "graphics_drm_wayland_files_hover"): "ok",
    ("scene_contract", "graphics_drm_wayland_files_scroll"): "ok",
    ("scene_contract", "graphics_drm_wayland_files_safe_preview"): "ok",
    ("scene_contract", "graphics_drm_wayland_files_wheel"): "ok",
    ("scene_contract", "graphics_drm_wayland_files_page_keys"): "ok",
    ("scene_contract", "graphics_drm_wayland_files_edge_keys"): "ok",
    ("scene_contract", "graphics_drm_wayland_files_scrollbar_drag"): "ok",
    ("scene_contract", "graphics_drm_wayland_files_preview_scroll"): "ok",
    ("scene_contract", "graphics_drm_wayland_input_dispatch"): "ok",
    ("scene_contract", "graphics_drm_wayland_external_client"): "ok",
    ("scene_contract", "graphics_drm_wayland_external_client_buffer"): "ok",
    ("scene_contract", "graphics_drm_wayland_third_party_client"): "ok",
    ("scene_contract", "graphics_drm_wayland_no_weston_compositor"): "ok",
    ("scene_contract", "graphics_drm_wayland_external_client_multi_surface"): "ok",
    ("scene_contract", "graphics_drm_wayland_external_client_independent_buffers"): "ok",
    ("scene_contract", "graphics_drm_wayland_external_client_composited"): "ok",
    ("scene_contract", "graphics_drm_wayland_external_client_frame_callback"): "ok",
    ("scene_contract", "graphics_drm_wayland_external_client_damage"): "ok",
    ("scene_contract", "graphics_drm_wayland_external_client_focus"): "ok",
    ("scene_contract", "graphics_drm_wayland_external_client_focus_change"): "ok",
    ("scene_contract", "graphics_drm_wayland_external_client_stacking"): "ok",
    ("scene_contract", "graphics_drm_wayland_stacking_repaint"): "ok",
    ("scene_contract", "graphics_drm_wayland_stacking_repaint_changed"): "ok",
    ("scene_contract", "graphics_drm_wayland_client_cleanup"): "ok",
    ("scene_contract", "graphics_drm_wayland_client_cleanup_focus"): "ok",
    ("scene_contract", "graphics_drm_wayland_client_cleanup_repaint"): "ok",
    ("scene_contract", "graphics_drm_wayland_interactive_geometry"): "ok",
    ("scene_contract", "graphics_drm_wayland_state_cycle"): "ok",
    ("scene_contract", "graphics_drm_wayland_state_configure"): "ok",
    ("scene_contract", "graphics_drm_wayland_close"): "ok",
    ("scene_contract", "graphics_drm_wayland_close_cleanup"): "ok",
    ("scene_contract", "graphics_drm_wayland_close_repaint"): "ok",
    ("scene_contract", "graphics_evdev_aqua_seat"): "ok",
    ("scene_contract", "graphics_evdev_keyboard"): "ok",
    ("scene_contract", "graphics_evdev_pointer_motion"): "ok",
    ("scene_contract", "graphics_evdev_pointer_button"): "ok",
    ("scene_contract", "graphics_evdev_launcher"): "ok",
    ("scene_contract", "graphics_drm_wayland_capture"): "ok",
    ("scene_contract", "graphics_drm_wayland_capture_dimensions"): "ok",
    ("scene_contract", "graphics_drm_wayland_ppm_checksum"): "ok",
    ("scene_contract", "graphics_drm_wayland_png_checksum"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_path_ready"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_observed_false"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_manual_observation"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_bounded"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_frames"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_display_started"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_display_stopped"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_no_persistent"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_no_desktop_shell"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_no_boot_graphics"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_no_autostart"): "ok",
    ("scene_contract", "graphics_qemu_visible_boot_recovery_safe"): "ok",
    ("scene_contract", "graphics_qemu_observation_marker"): "ok",
    ("scene_contract", "graphics_qemu_observation_marker_ready"): "ok",
    ("scene_contract", "graphics_qemu_observation_marker_source"): "ok",
    ("scene_contract", "graphics_qemu_observation_marker_path_ready"): "ok",
    ("scene_contract", "graphics_qemu_observation_marker_not_observed"): "ok",
    ("scene_contract", "graphics_qemu_observation_marker_status_not_observed"): "ok",
    ("scene_contract", "graphics_qemu_observation_marker_recorded"): "ok",
    ("scene_contract", "graphics_qemu_observation_marker_operator"): "ok",
    ("scene_contract", "graphics_qemu_observation_marker_no_persistent"): "ok",
    ("scene_contract", "graphics_qemu_observation_marker_no_boot_graphics"): "ok",
    ("scene_contract", "graphics_qemu_observation_marker_no_autostart"): "ok",
    ("scene_contract", "graphics_qemu_observation_marker_recovery_safe"): "ok",
    ("scene_contract", "qemu_visible_evidence_record"): "ok",
    ("scene_contract", "qemu_visible_evidence_record_ready"): "ok",
    ("scene_contract", "qemu_visible_evidence_record_status"): "ok",
    ("scene_contract", "qemu_visible_evidence_record_capture"): "ok",
    ("scene_contract", "qemu_visible_evidence_record_manual"): "ok",
    ("scene_contract", "qemu_visible_evidence_record_allows_observation"): "ok",
    ("scene_contract", "qemu_visible_evidence_record_no_persistent"): "ok",
    ("scene_contract", "qemu_visible_evidence_record_no_boot_graphics"): "ok",
    ("scene_contract", "qemu_visible_evidence_record_no_autostart"): "ok",
    ("scene_contract", "qemu_visible_evidence_record_recovery_safe"): "ok",
    ("scene_contract", "graphics_qemu_observation_positive"): "ok",
    ("scene_contract", "graphics_qemu_observation_positive_ready"): "ok",
    ("scene_contract", "graphics_qemu_observation_positive_source"): "ok",
    ("scene_contract", "graphics_qemu_observation_positive_path_ready"): "ok",
    ("scene_contract", "graphics_qemu_observation_positive_observed"): "ok",
    ("scene_contract", "graphics_qemu_observation_positive_status_observed"): "ok",
    ("scene_contract", "graphics_qemu_observation_positive_evidence_required"): "ok",
    ("scene_contract", "graphics_qemu_observation_positive_evidence_recorded"): "ok",
    ("scene_contract", "graphics_qemu_observation_positive_recorded"): "ok",
    ("scene_contract", "graphics_qemu_observation_positive_no_persistent"): "ok",
    ("scene_contract", "graphics_qemu_observation_positive_no_boot_graphics"): "ok",
    ("scene_contract", "graphics_qemu_observation_positive_no_autostart"): "ok",
    ("scene_contract", "graphics_qemu_observation_positive_recovery_safe"): "ok",
    ("scene_contract", "qemu_visible_pass_report"): "ok",
    ("scene_contract", "qemu_visible_pass_report_ready"): "ok",
    ("scene_contract", "qemu_visible_pass_report_source_attempt"): "ok",
    ("scene_contract", "qemu_visible_pass_report_source_observation"): "ok",
    ("scene_contract", "qemu_visible_pass_report_observed"): "ok",
    ("scene_contract", "qemu_visible_pass_report_attempt_completed"): "ok",
    ("scene_contract", "qemu_visible_pass_report_evidence_required"): "ok",
    ("scene_contract", "qemu_visible_pass_report_evidence_recorded"): "ok",
    ("scene_contract", "qemu_visible_pass_report_evidence_rule"): "ok",
    ("scene_contract", "qemu_visible_pass_report_no_persistent"): "ok",
    ("scene_contract", "qemu_visible_pass_report_no_boot_graphics"): "ok",
    ("scene_contract", "qemu_visible_pass_report_no_autostart"): "ok",
    ("scene_contract", "qemu_visible_pass_report_recovery_safe"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_ready"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_host"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_ready_capture_flow"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_script"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_no_docker"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_manual_observation"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_evidence_required"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_observation_rule"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_pass_report_required"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_bounded"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_no_persistent"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_no_boot_graphics"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_no_autostart"): "ok",
    ("scene_contract", "qemu_visible_manual_runbook_recovery_safe"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_ready"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_waiting"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_not_observed"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_no_evidence"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_no_boot_graphics"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_no_autostart"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_recovery_safe"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_preflight_verified"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_capture_hash_verified"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_positive"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_positive_applied"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_positive_evidence"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_positive_observed"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_positive_no_persistent"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_positive_no_boot_graphics"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_positive_no_autostart"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_positive_recovery_safe"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_positive_preflight_verified"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_positive_capture_hash_verified"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_missing_preflight_rejected"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_missing_preflight_status"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_missing_preflight_verified"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_missing_preflight_exit"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_missing_preflight_not_observed"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_missing_preflight_unverified"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_missing_capture_hash_rejected"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_missing_capture_hash_status"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_missing_capture_hash_value"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_missing_capture_hash_preflight_verified"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_missing_capture_hash_exit"): "ok",
    ("scene_contract", "qemu_visible_evidence_bundle_apply_missing_capture_hash_not_observed"): "ok",
    ("scene_contract", "visible_preview_plan"): "ok",
    ("scene_contract", "visible_preview_output"): "ok",
    ("scene_contract", "visible_preview_frame_buffer"): "ok",
    ("scene_contract", "visible_preview_raster"): "ok",
    ("scene_contract", "visible_preview_png_export"): "ok",
    ("scene_contract", "visible_preview_client_layer_pipeline"): "ok",
    ("scene_contract", "visible_preview_client_layer_count"): "ok",
    ("scene_contract", "visible_preview_client_layer_checksum"): "ok",
    ("scene_contract", "visible_preview_client_layer_buffer_snapshot"): "ok",
    ("scene_contract", "visible_preview_client_layer_snapshot_mode"): "ok",
    ("scene_contract", "visible_preview_window_not_started"): "ok",
    ("scene_contract", "visible_preview_export"): "ok",
    ("scene_contract", "visible_preview_export_format"): "ok",
    ("scene_contract", "visible_preview_export_bytes"): "ok",
    ("scene_contract", "visible_preview_export_checksum"): "ok",
    ("scene_contract", "visible_preview_export_client_layers"): "ok",
    ("scene_contract", "visible_preview_export_client_layers_composited"): "ok",
    ("scene_contract", "visible_preview_export_client_layer_buffer_snapshot"): "ok",
    ("scene_contract", "visible_preview_export_client_layer_snapshot_mode"): "ok",
    ("scene_contract", "visible_preview_export_png_checksum"): "ok",
    ("scene_contract", "nested_preview_loop"): "ok",
    ("scene_contract", "nested_preview_frame_clock"): "ok",
    ("scene_contract", "nested_preview_frames"): "ok",
    ("scene_contract", "nested_preview_manual"): "ok",
    ("scene_contract", "nested_preview_no_autostart"): "ok",
    ("scene_contract", "client_window_model"): "ok",
    ("scene_contract", "client_window_focus"): "ok",
    ("scene_contract", "client_window_move"): "ok",
    ("scene_contract", "client_window_resize"): "ok",
    ("scene_contract", "client_window_close"): "ok",
    ("scene_contract", "client_window_stacking"): "ok",
    ("scene_contract", "client_window_chrome"): "ok",
    ("scene_contract", "client_window_no_real_client"): "ok",
    ("scene_contract", "client_surface_lifecycle"): "ok",
    ("scene_contract", "client_surface_configure"): "ok",
    ("scene_contract", "client_surface_commit"): "ok",
    ("scene_contract", "client_surface_map"): "ok",
    ("scene_contract", "client_surface_focus"): "ok",
    ("scene_contract", "client_surface_unmap"): "ok",
    ("scene_contract", "client_surface_destroy"): "ok",
    ("scene_contract", "client_surface_geometry"): "ok",
    ("scene_contract", "client_surface_no_real_client"): "ok",
    ("scene_contract", "client_surface_registry"): "ok",
    ("scene_contract", "client_surface_registry_source"): "ok",
    ("scene_contract", "client_surface_registry_record"): "ok",
    ("scene_contract", "client_surface_registry_active"): "ok",
    ("scene_contract", "client_surface_registry_configure"): "ok",
    ("scene_contract", "client_surface_registry_lifecycle"): "ok",
    ("scene_contract", "client_surface_registry_two_client"): "ok",
    ("scene_contract", "client_surface_registry_focus"): "ok",
    ("scene_contract", "client_surface_registry_stacking"): "ok",
    ("scene_contract", "client_surface_registry_close"): "ok",
    ("scene_contract", "client_surface_registry_buffer_metadata"): "ok",
    ("scene_contract", "client_surface_registry_buffer_import_plan"): "ok",
    ("scene_contract", "client_surface_registry_sample_pixel"): "ok",
    ("scene_contract", "client_surface_registry_sample_grid"): "ok",
    ("scene_contract", "client_surface_registry_buffer_snapshot"): "ok",
    ("scene_contract", "client_surface_registry_no_render"): "ok",
    ("scene_contract", "renderer_surface_sources"): "ok",
    ("scene_contract", "renderer_surface_sources_registry"): "ok",
    ("scene_contract", "renderer_surface_sources_count"): "ok",
    ("scene_contract", "renderer_surface_sources_active"): "ok",
    ("scene_contract", "renderer_surface_sources_import"): "ok",
    ("scene_contract", "renderer_surface_sources_z_order"): "ok",
    ("scene_contract", "renderer_surface_sources_sample_pixel"): "ok",
    ("scene_contract", "renderer_surface_sources_sample_grid"): "ok",
    ("scene_contract", "renderer_surface_sources_buffer_snapshot"): "ok",
    ("scene_contract", "client_layer_pipeline"): "ok",
    ("scene_contract", "client_layer_source_plan"): "ok",
    ("scene_contract", "client_layer_paint_plan"): "ok",
    ("scene_contract", "client_layer_raster"): "ok",
    ("scene_contract", "client_layer_count"): "ok",
    ("scene_contract", "client_layer_checksum"): "ok",
    ("scene_contract", "client_layer_sample_pixel"): "ok",
    ("scene_contract", "client_layer_sample_grid"): "ok",
    ("scene_contract", "client_layer_buffer_snapshot"): "ok",
    ("scene_contract", "xdg_shell_binding"): "ok",
    ("scene_contract", "xdg_shell_protocol"): "ok",
    ("scene_contract", "xdg_shell_handler"): "ok",
    ("scene_contract", "xdg_shell_global"): "ok",
    ("scene_contract", "xdg_shell_toplevel_callbacks"): "ok",
    ("scene_contract", "xdg_shell_popup_callbacks"): "ok",
    ("scene_contract", "xdg_shell_no_real_client"): "ok",
    ("scene_contract", "xdg_toplevel_client"): "ok",
    ("scene_contract", "xdg_toplevel_client_connected"): "ok",
    ("scene_contract", "xdg_toplevel_client_inserted"): "ok",
    ("scene_contract", "xdg_toplevel_client_registry"): "ok",
    ("scene_contract", "xdg_toplevel_client_globals"): "ok",
    ("scene_contract", "xdg_toplevel_shm_global"): "ok",
    ("scene_contract", "xdg_toplevel_shm_buffer"): "ok",
    ("scene_contract", "xdg_toplevel_client_buffer_attach"): "ok",
    ("scene_contract", "xdg_toplevel_surface"): "ok",
    ("scene_contract", "xdg_toplevel_request"): "ok",
    ("scene_contract", "xdg_toplevel_server_buffer_attach"): "ok",
    ("scene_contract", "xdg_toplevel_shm_import"): "ok",
    ("scene_contract", "xdg_toplevel_shm_sample"): "ok",
    ("scene_contract", "xdg_toplevel_shm_sample_pixel"): "ok",
    ("scene_contract", "xdg_toplevel_shm_sample_grid"): "ok",
    ("scene_contract", "xdg_toplevel_shm_buffer_snapshot"): "ok",
    ("scene_contract", "xdg_toplevel_server_created"): "ok",
    ("scene_contract", "xdg_toplevel_no_boot_graphics"): "ok",
    ("scene_contract", "xdg_toplevel_configure_ack"): "ok",
    ("scene_contract", "xdg_toplevel_close_event"): "ok",
    ("scene_contract", "xdg_toplevel_client_count"): "ok",
    ("scene_contract", "xdg_toplevel_window_model"): "ok",
    ("scene_contract", "xdg_toplevel_window_source"): "ok",
    ("scene_contract", "xdg_toplevel_window_surface_bound"): "ok",
    ("scene_contract", "xdg_toplevel_window_model_bound"): "ok",
    ("scene_contract", "xdg_toplevel_window_count"): "ok",
    ("scene_contract", "xdg_toplevel_window_two_model"): "ok",
    ("scene_contract", "xdg_toplevel_window_stacking"): "ok",
    ("scene_contract", "xdg_toplevel_window_chrome"): "ok",
    ("scene_contract", "xdg_toplevel_window_no_render"): "ok",
    ("scene_contract", "smithay_launcher_seat"): "ok",
    ("scene_contract", "smithay_launcher_seat_global"): "ok",
    ("scene_contract", "smithay_launcher_seat_input"): "ok",
    ("scene_contract", "smithay_launcher_seat_rootfs"): "ok",
    ("scene_contract", "scene_status"): "ok",
    ("scene_contract", "render_plan"): "ok",
    ("scene_contract", "paint_plan"): "ok",
    ("scene_contract", "paint_steps"): "ok",
    ("scene_contract", "paint_order"): "ok",
    ("scene_contract", "paint_surface"): "ok",
    ("scene_contract", "frame_plan"): "ok",
    ("scene_contract", "frame_format"): "ok",
    ("scene_contract", "frame_stride"): "ok",
    ("scene_contract", "frame_damage"): "ok",
    ("scene_contract", "frame_buffer"): "ok",
    ("scene_contract", "frame_buffer_bytes"): "ok",
    ("scene_contract", "frame_buffer_clear"): "ok",
    ("scene_contract", "raster"): "ok",
    ("scene_contract", "raster_rects"): "ok",
    ("scene_contract", "raster_wallpaper_sample"): "ok",
    ("scene_contract", "raster_surface_sample"): "ok",
    ("scene_contract", "raster_surface_border_sample"): "ok",
    ("scene_contract", "raster_surface_highlight_sample"): "ok",
    ("scene_contract", "raster_surface_corner_sample"): "ok",
    ("scene_contract", "raster_surface_shadow_sample"): "ok",
    ("scene_contract", "surface_primitives"): "ok",
    ("scene_contract", "raster_checksum"): "ok",
    ("scene_contract", "raster_export"): "ok",
    ("scene_contract", "raster_export_format"): "ok",
    ("scene_contract", "raster_export_bytes"): "ok",
    ("scene_contract", "raster_export_checksum"): "ok",
    ("scene_contract", "raster_png_export"): "ok",
    ("scene_contract", "raster_png_export_format"): "ok",
    ("scene_contract", "raster_png_export_bytes"): "ok",
    ("scene_contract", "raster_png_export_checksum"): "ok",
    ("scene_contract", "desktop_shell"): "not_started",
    ("boot_markers", "session_config"): "ok",
    ("boot_markers", "fbdev_device"): "ok",
    ("boot_markers", "session_runtime"): "ok",
    ("boot_markers", "session_env"): "ok",
    ("boot_markers", "session_bootstrap"): "ok",
    ("boot_markers", "compositor_assets"): "ok",
    ("boot_markers", "output_plan"): "ok",
    ("boot_markers", "visible_preview_plan"): "ok",
    ("boot_markers", "scene_contract"): "ok",
    ("boot_markers", "render_plan"): "ok",
    ("boot_markers", "paint_plan"): "ok",
    ("boot_markers", "frame_plan"): "ok",
    ("boot_markers", "frame_buffer"): "ok",
    ("boot_markers", "raster"): "ok",
    ("boot_markers", "surface_primitives"): "ok",
    ("boot_markers", "raster_export"): "ok",
    ("boot_markers", "raster_png_export"): "ok",
    ("boot_markers", "session_check"): "ok",
    ("boot_markers", "recovery_ready"): "ok",
    ("boot_summary", "status"): "ok",
    ("boot_summary", "fbdev_device"): "ok",
    ("boot_summary", "session_config"): "ok",
    ("boot_summary", "session_runtime"): "ok",
    ("boot_summary", "session_env"): "ok",
    ("boot_summary", "session_bootstrap"): "ok",
    ("boot_summary", "compositor_assets"): "ok",
    ("boot_summary", "output_plan"): "ok",
    ("boot_summary", "visible_preview_plan"): "ok",
    ("boot_summary", "scene_contract"): "ok",
    ("boot_summary", "render_plan"): "ok",
    ("boot_summary", "paint_plan"): "ok",
    ("boot_summary", "frame_plan"): "ok",
    ("boot_summary", "frame_buffer"): "ok",
    ("boot_summary", "raster"): "ok",
    ("boot_summary", "surface_primitives"): "ok",
    ("boot_summary", "raster_export"): "ok",
    ("boot_summary", "raster_png_export"): "ok",
    ("boot_summary", "session_check"): "ok",
    ("boot_summary", "recovery_ready"): "ok",
}

errors = []
for keys, expected_value in expected.items():
    current = manifest
    for key in keys:
        if not isinstance(current, dict) or key not in current:
            errors.append(f"missing {'.'.join(keys)}")
            break
        current = current[key]
    else:
        if current != expected_value:
            errors.append(
                f"{'.'.join(keys)} expected {expected_value!r}, got {current!r}"
            )

generated_at = manifest.get("generated_at_utc", "")
if not generated_at.endswith("Z") or "T" not in generated_at:
    errors.append("generated_at_utc must be UTC ISO-like timestamp ending in Z")

png_bytes = manifest.get("artifacts", {}).get("fbdev_qemu_png", {}).get("bytes", "")
if not str(png_bytes).isdigit() or int(png_bytes) <= 0:
    errors.append("artifacts.fbdev_qemu_png.bytes must be a positive integer")

if errors:
    for error in errors:
        print(f"manifest error: {error}", file=sys.stderr)
    sys.exit(1)

print("Aqua Linux JSON image manifest checks passed.")
PY
