#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
cd "${ROOT_DIR}"

for file in LICENSE ASSET_LICENSE.md THIRD_PARTY_LICENSES.md CONTRIBUTING.md SECURITY.md README.md; do
    test -s "${file}" || {
        echo "Missing public repository file: ${file}" >&2
        exit 1
    }
done

grep -Fq '/website/' .gitignore
grep -Fq '/target/' .gitignore
grep -Fq '/build/' .gitignore
grep -Fq '*.qcow2' .gitignore
grep -Fq '*.img' .gitignore

if find . \
    -path './website' -prune -o \
    -path './target' -prune -o \
    -path './build' -prune -o \
    -name '.DS_Store' -print | grep -q .; then
    echo "Unignored .DS_Store file found" >&2
    exit 1
fi

if find . \
    -path './website' -prune -o \
    -path './target' -prune -o \
    -path './build' -prune -o \
    -type d -name '__pycache__' -print | grep -q .; then
    echo "Unignored Python cache found" >&2
    exit 1
fi

test -z "$(cargo metadata --format-version 1 |
    jq -r '.packages[] | select(.license == null or .license == "") | .name')"

grep -Fq 'license = "MIT"' Cargo.toml
if grep -Fq 'example.invalid' Cargo.toml README.md; then
    echo "Placeholder repository URL found" >&2
    exit 1
fi

ai_attribution_pattern='chat''gpt|open''ai|co''dex|clau''de|co''pilot|gem''ini|generated by a''i|a''i-generated'
if grep -RniE \
    --exclude='Cargo.lock' \
    --exclude-dir=target \
    --exclude-dir=build \
    --exclude-dir=website \
    --exclude-dir=local-references \
    "${ai_attribution_pattern}" \
    .; then
    echo "AI-assistant attribution found in public source payload" >&2
    exit 1
fi

grep -Fxq '/docs/aqua-linux/local-references/' .gitignore
if git rev-parse --is-inside-work-tree >/dev/null 2>&1 &&
    test -n "$(git ls-files docs/aqua-linux/local-references)"; then
    echo "Private reference boards are tracked by Git" >&2
    exit 1
fi
if find docs/aqua-linux/assets -maxdepth 1 -name 'reference-*.png' | grep -q .; then
    echo "Private reference board found in public asset directory" >&2
    exit 1
fi

test ! -e docs/aqua-linux/assets/aqua-brand-board.png
for brand_asset in symbol-primary symbol-inverse symbol-accent wordmark-primary logo-primary; do
    test -s "docs/aqua-linux/assets/aqua-${brand_asset}.png"
done

grep -Fq '"defaultTheme": "LightWhite"' docs/aqua-linux/design-tokens.json
grep -Fq '"Softtouch"' docs/aqua-linux/design-tokens.json
grep -Fq '"Deepside"' docs/aqua-linux/design-tokens.json
grep -Fq '"Nightmare"' docs/aqua-linux/design-tokens.json

calculated_percent="$(jq '[.phases[].percent] | (((add / length) + 0.5) | floor)' docs/aqua-linux/progress.json)"
reported_percent="$(jq '.overallPercent' docs/aqua-linux/progress.json)"
test "${calculated_percent}" = "${reported_percent}" || {
    echo "Overall progress does not match the documented public formula" >&2
    exit 1
}

grep -Fq 'Private concept boards' README.md
grep -Fq 'excluded from Git' docs/aqua-linux/ui-contract.md
grep -Fq 'not ready for installation' README.md
grep -Fq 'daily-use machine' README.md
grep -Fq 'publication and distribution rights' ASSET_LICENSE.md
grep -Fq 'legal-info' docs/aqua-linux/license-audit.md

echo "Aqua Linux public repository checks passed."
