#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="${ROOT_DIR}/build/buildroot-output"
IMAGE_DIR="${OUTPUT_DIR}/images"
SERIAL_LOG="${ROOT_DIR}/build/qemu-serial-check.log"
FBDEV_QEMU_LOG="${ROOT_DIR}/build/qemu-fbdev-present-check.log"
GRAPHICAL_BOOT_QEMU_LOG="${ROOT_DIR}/build/qemu-graphical-boot-check.log"
LIVE_THEME_QEMU_LOG="${ROOT_DIR}/build/qemu-live-theme-check.log"
THEME_LIGHT_SCREENSHOT="${ROOT_DIR}/build/qemu-theme-light.png"
THEME_DEEP_SCREENSHOT="${ROOT_DIR}/build/qemu-theme-dark.png"
FBDEV_QEMU_CAPTURE="${ROOT_DIR}/build/qemu-fbdev-present-capture.txt"
FBDEV_QEMU_PPM="${ROOT_DIR}/build/qemu-fbdev-present.ppm"
FBDEV_QEMU_PNG="${ROOT_DIR}/build/qemu-fbdev-present.png"
FBDEV_QEMU_SHA256="${ROOT_DIR}/build/qemu-fbdev-present.sha256"
KMS_QEMU_CAPTURE="${ROOT_DIR}/build/qemu-drm-kms-present-capture.txt"
KMS_QEMU_PPM="${ROOT_DIR}/build/qemu-drm-kms-present.ppm"
KMS_QEMU_PNG="${ROOT_DIR}/build/qemu-drm-kms-present.png"
KMS_QEMU_SHA256="${ROOT_DIR}/build/qemu-drm-kms-present.sha256"
PAGE_FLIP_QEMU_CAPTURE="${ROOT_DIR}/build/qemu-drm-page-flip-present-capture.txt"
PAGE_FLIP_QEMU_PPM="${ROOT_DIR}/build/qemu-drm-page-flip-present.ppm"
PAGE_FLIP_QEMU_PNG="${ROOT_DIR}/build/qemu-drm-page-flip-present.png"
PAGE_FLIP_QEMU_SHA256="${ROOT_DIR}/build/qemu-drm-page-flip-present.sha256"
FRAME_LOOP_QEMU_CAPTURE="${ROOT_DIR}/build/qemu-drm-frame-loop-capture.txt"
FRAME_LOOP_QEMU_PPM="${ROOT_DIR}/build/qemu-drm-frame-loop.ppm"
FRAME_LOOP_QEMU_PNG="${ROOT_DIR}/build/qemu-drm-frame-loop.png"
FRAME_LOOP_QEMU_SHA256="${ROOT_DIR}/build/qemu-drm-frame-loop.sha256"
SESSION_LOOP_QEMU_CAPTURE="${ROOT_DIR}/build/qemu-drm-session-loop-capture.txt"
SESSION_LOOP_QEMU_PPM="${ROOT_DIR}/build/qemu-drm-session-loop.ppm"
SESSION_LOOP_QEMU_PNG="${ROOT_DIR}/build/qemu-drm-session-loop.png"
SESSION_LOOP_QEMU_SHA256="${ROOT_DIR}/build/qemu-drm-session-loop.sha256"
WAYLAND_SESSION_QEMU_CAPTURE="${ROOT_DIR}/build/qemu-drm-wayland-session-capture.txt"
WAYLAND_SESSION_QEMU_PPM="${ROOT_DIR}/build/qemu-drm-wayland-session.ppm"
WAYLAND_SESSION_QEMU_PNG="${ROOT_DIR}/build/qemu-drm-wayland-session.png"
WAYLAND_SESSION_QEMU_SHA256="${ROOT_DIR}/build/qemu-drm-wayland-session.sha256"
MANIFEST="${ROOT_DIR}/build/aqua-image-manifest.txt"
MANIFEST_JSON="${ROOT_DIR}/build/aqua-image-manifest.json"
BOOT_SUMMARY="${ROOT_DIR}/build/aqua-boot-summary.txt"
BOOT_SUMMARY_JSON="${ROOT_DIR}/build/aqua-boot-summary.json"
QEMU_VISIBLE_STATUS="${ROOT_DIR}/build/qemu-visible-status.txt"
QEMU_VISIBLE_STATUS_JSON="${ROOT_DIR}/build/qemu-visible-status.json"
QEMU_VISIBLE_OPERATOR_PLAN="${ROOT_DIR}/build/qemu-visible-operator-plan.txt"
QEMU_VISIBLE_OPERATOR_PLAN_JSON="${ROOT_DIR}/build/qemu-visible-operator-plan.json"
QEMU_VISIBLE_OPERATOR_PACKET="${ROOT_DIR}/build/qemu-visible-operator-packet.txt"
QEMU_VISIBLE_OPERATOR_PACKET_JSON="${ROOT_DIR}/build/qemu-visible-operator-packet.json"
QEMU_VISIBLE_OPERATOR_CHECKLIST="${ROOT_DIR}/build/qemu-visible-operator-checklist.md"
QEMU_VISIBLE_OPERATOR_PASS="${ROOT_DIR}/build/qemu-visible-operator-pass.txt"
QEMU_VISIBLE_OPERATOR_PASS_JSON="${ROOT_DIR}/build/qemu-visible-operator-pass.json"
FIRST_GRAPHICS_SESSION_STATUS="${ROOT_DIR}/build/first-graphics-session-status.txt"
FIRST_GRAPHICS_SESSION_STATUS_JSON="${ROOT_DIR}/build/first-graphics-session-status.json"
CONTRACT_DIR="${ROOT_DIR}/build/rootfs-compositor-contract"

report_file() {
    label="$1"
    path="$2"

    if [ -f "${path}" ]; then
        size="$(wc -c < "${path}" | tr -d ' ')"
        printf 'ready: %-16s %s bytes  %s\n' "${label}" "${size}" "${path}"
    else
        printf 'missing: %-14s %s\n' "${label}" "${path}"
    fi
}

manifest_value() {
    key="$1"

    if [ -f "${MANIFEST}" ]; then
        value="$(grep -F "${key}=" "${MANIFEST}" 2>/dev/null | tail -n 1 | sed "s/^${key}=//")"
        if [ -n "${value}" ]; then
            printf '%s' "${value}"
            return
        fi
    fi

    printf 'unknown'
}

report_status() {
    label="$1"
    key="$2"
    printf 'status: %-28s %s\n' "${label}" "$(manifest_value "${key}")"
}

echo "Aqua Linux artifact report"
echo
report_file "kernel" "${IMAGE_DIR}/bzImage"
report_file "rootfs" "${IMAGE_DIR}/rootfs.ext2"
report_file "disk" "${IMAGE_DIR}/disk.img"
report_file "rootfs tar" "${IMAGE_DIR}/rootfs.tar"
report_file "build config" "${OUTPUT_DIR}/.config"
report_file "serial log" "${SERIAL_LOG}"
report_file "theme QEMU log" "${LIVE_THEME_QEMU_LOG}"
report_file "theme light" "${THEME_LIGHT_SCREENSHOT}"
report_file "theme deep" "${THEME_DEEP_SCREENSHOT}"
report_file "fbdev qemu log" "${FBDEV_QEMU_LOG}"
report_file "graphical boot log" "${GRAPHICAL_BOOT_QEMU_LOG}"
report_file "fbdev capture" "${FBDEV_QEMU_CAPTURE}"
report_file "fbdev ppm" "${FBDEV_QEMU_PPM}"
report_file "fbdev png" "${FBDEV_QEMU_PNG}"
report_file "fbdev sha256" "${FBDEV_QEMU_SHA256}"
report_file "KMS capture" "${KMS_QEMU_CAPTURE}"
report_file "KMS ppm" "${KMS_QEMU_PPM}"
report_file "KMS png" "${KMS_QEMU_PNG}"
report_file "KMS sha256" "${KMS_QEMU_SHA256}"
report_file "page flip capture" "${PAGE_FLIP_QEMU_CAPTURE}"
report_file "page flip ppm" "${PAGE_FLIP_QEMU_PPM}"
report_file "page flip png" "${PAGE_FLIP_QEMU_PNG}"
report_file "page flip sha256" "${PAGE_FLIP_QEMU_SHA256}"
report_file "frame loop capture" "${FRAME_LOOP_QEMU_CAPTURE}"
report_file "frame loop ppm" "${FRAME_LOOP_QEMU_PPM}"
report_file "frame loop png" "${FRAME_LOOP_QEMU_PNG}"
report_file "frame loop sha256" "${FRAME_LOOP_QEMU_SHA256}"
report_file "session loop capture" "${SESSION_LOOP_QEMU_CAPTURE}"
report_file "session loop ppm" "${SESSION_LOOP_QEMU_PPM}"
report_file "session loop png" "${SESSION_LOOP_QEMU_PNG}"
report_file "session loop sha256" "${SESSION_LOOP_QEMU_SHA256}"
report_file "Wayland session capture" "${WAYLAND_SESSION_QEMU_CAPTURE}"
report_file "Wayland session ppm" "${WAYLAND_SESSION_QEMU_PPM}"
report_file "Wayland session png" "${WAYLAND_SESSION_QEMU_PNG}"
report_file "Wayland session sha256" "${WAYLAND_SESSION_QEMU_SHA256}"
report_file "boot summary" "${BOOT_SUMMARY}"
report_file "boot json" "${BOOT_SUMMARY_JSON}"
report_file "manifest" "${MANIFEST}"
report_file "manifest json" "${MANIFEST_JSON}"
report_file "qemu visible status" "${QEMU_VISIBLE_STATUS}"
report_file "qemu visible json" "${QEMU_VISIBLE_STATUS_JSON}"
report_file "qemu operator plan" "${QEMU_VISIBLE_OPERATOR_PLAN}"
report_file "qemu operator json" "${QEMU_VISIBLE_OPERATOR_PLAN_JSON}"
report_file "qemu operator packet" "${QEMU_VISIBLE_OPERATOR_PACKET}"
report_file "qemu packet json" "${QEMU_VISIBLE_OPERATOR_PACKET_JSON}"
report_file "qemu checklist" "${QEMU_VISIBLE_OPERATOR_CHECKLIST}"
report_file "qemu pass" "${QEMU_VISIBLE_OPERATOR_PASS}"
report_file "qemu pass json" "${QEMU_VISIBLE_OPERATOR_PASS_JSON}"
report_file "first graphics" "${FIRST_GRAPHICS_SESSION_STATUS}"
report_file "first graphics json" "${FIRST_GRAPHICS_SESSION_STATUS_JSON}"
report_file "session check" "${CONTRACT_DIR}/session-check.txt"
report_file "output plan" "${CONTRACT_DIR}/output-plan-probe.txt"
report_file "output handoff" "${CONTRACT_DIR}/display-output-handoff-probe.txt"
report_file "activation plan" "${CONTRACT_DIR}/display-activation-plan-probe.txt"
report_file "manual launch" "${CONTRACT_DIR}/manual-launch-plan.txt"
report_file "guarded run" "${CONTRACT_DIR}/guarded-run.txt"
report_file "session supervisor" "${CONTRACT_DIR}/graphical-session-supervisor.txt"
report_file "graphics boot gate" "${CONTRACT_DIR}/graphical-session-boot.txt"
report_file "handoff gate" "${CONTRACT_DIR}/handoff-gate.txt"
report_file "display smoke" "${CONTRACT_DIR}/display-output-smoke.txt"
report_file "nested surface" "${CONTRACT_DIR}/nested-output-surface.txt"
report_file "visible preview" "${CONTRACT_DIR}/visible-preview-plan-probe.txt"
report_file "preview html" "${CONTRACT_DIR}/aqua-visible-preview.html"
report_file "nested loop" "${CONTRACT_DIR}/nested-preview-loop.txt"
report_file "manual backend" "${CONTRACT_DIR}/manual-nested-preview-backend.txt"
report_file "manual execution" "${CONTRACT_DIR}/manual-nested-preview-execution.txt"
report_file "execution probe" "${CONTRACT_DIR}/manual-nested-preview-execution-probe.txt"
report_file "preview request" "${CONTRACT_DIR}/visible-preview-request.txt"
report_file "preview launcher" "${CONTRACT_DIR}/visible-preview-launch.txt"
report_file "recovery help" "${CONTRACT_DIR}/recovery-help.txt"
report_file "operator transcript" "${CONTRACT_DIR}/operator-transcript.txt"
report_file "graphics gate" "${CONTRACT_DIR}/graphics-enable-gate.txt"
report_file "graphics allow" "${CONTRACT_DIR}/graphics-enable-gate-positive.txt"
report_file "graphics candidate" "${CONTRACT_DIR}/graphics-launch-candidate.txt"
report_file "rollback drill" "${CONTRACT_DIR}/graphics-rollback-drill.txt"
report_file "startup preflight" "${CONTRACT_DIR}/graphics-startup-preflight.txt"
report_file "startup rehearsal" "${CONTRACT_DIR}/graphics-startup-rehearsal.txt"
report_file "qemu display gate" "${CONTRACT_DIR}/graphics-qemu-display-gate.txt"
report_file "visible qemu attempt" "${CONTRACT_DIR}/graphics-visible-qemu-attempt.txt"
report_file "visible transcript" "${CONTRACT_DIR}/graphics-visible-attempt-transcript.txt"
report_file "visible result" "${CONTRACT_DIR}/graphics-visible-attempt-result.txt"
report_file "visible runner" "${CONTRACT_DIR}/graphics-visible-attempt-runner.txt"
report_file "qemu visible boot" "${CONTRACT_DIR}/graphics-qemu-visible-boot-check.txt"
report_file "graphics fbdev" "${CONTRACT_DIR}/graphics-fbdev-present.txt"
report_file "drm device probe" "${CONTRACT_DIR}/drm-device-probe.txt"
report_file "qemu observation" "${CONTRACT_DIR}/graphics-qemu-observation-marker.txt"
report_file "qemu evidence" "${CONTRACT_DIR}/qemu-visible-evidence-record.txt"
report_file "qemu observed" "${CONTRACT_DIR}/graphics-qemu-observation-positive.txt"
report_file "qemu pass report" "${CONTRACT_DIR}/qemu-visible-pass-report.txt"
report_file "qemu runbook" "${CONTRACT_DIR}/qemu-visible-manual-runbook.txt"
report_file "qemu bundle apply" "${CONTRACT_DIR}/qemu-visible-evidence-bundle-apply.txt"
report_file "qemu bundle observed" "${CONTRACT_DIR}/qemu-visible-evidence-bundle-apply-positive.txt"
report_file "qemu bundle rejected" "${CONTRACT_DIR}/qemu-visible-evidence-bundle-apply-missing-preflight.txt"
report_file "qemu hash rejected" "${CONTRACT_DIR}/qemu-visible-evidence-bundle-apply-missing-capture-hash.txt"
report_file "client model" "${CONTRACT_DIR}/client-window-model-probe.txt"
report_file "client lifecycle" "${CONTRACT_DIR}/client-surface-lifecycle-probe.txt"
report_file "client registry" "${CONTRACT_DIR}/client-surface-registry-probe.txt"
report_file "renderer sources" "${CONTRACT_DIR}/renderer-surface-sources-probe.txt"
report_file "renderer backend" "${CONTRACT_DIR}/renderer-backend-probe.txt"
report_file "client layers" "${CONTRACT_DIR}/client-layer-pipeline-probe.txt"
report_file "xdg shell" "${CONTRACT_DIR}/xdg-shell-binding-probe.txt"
report_file "xdg client" "${CONTRACT_DIR}/xdg-toplevel-client-probe.txt"
report_file "xdg window" "${CONTRACT_DIR}/xdg-toplevel-window-model-probe.txt"
report_file "frame buffer" "${CONTRACT_DIR}/frame-buffer-probe.txt"
report_file "raster" "${CONTRACT_DIR}/raster-probe.txt"
report_file "raster ppm" "${CONTRACT_DIR}/aqua-raster.ppm"
report_file "raster png" "${CONTRACT_DIR}/aqua-raster.png"

if [ -f "${MANIFEST}" ]; then
    echo
    echo "Aqua Linux contract summary"
    report_status "rootfs session config" "session_config_recovery_safe"
    report_status "rootfs session env" "session_env_recovery_safe"
    report_status "compositor packaged" "compositor_packaged"
    report_status "session bootstrap probe" "session_bootstrap_probe"
    report_status "aggregate session check" "session_check_probe"
    report_status "output plan" "output_plan"
    report_status "output handoff" "display_output_handoff"
    report_status "activation plan" "display_activation_plan"
    report_status "manual launch plan" "manual_launch_plan"
    report_status "guarded run" "guarded_run"
    report_status "handoff gate" "handoff_gate"
    report_status "display smoke" "display_output_smoke"
    report_status "nested output surface" "nested_output_surface"
    report_status "visible preview plan" "visible_preview_plan"
    report_status "visible preview export" "visible_preview_export"
    report_status "nested preview loop" "nested_preview_loop"
    report_status "manual nested backend" "manual_nested_preview_backend"
    report_status "manual nested execution" "manual_nested_preview_execution"
    report_status "visible preview request" "visible_preview_request"
    report_status "visible preview launcher" "visible_preview_launch"
    report_status "recovery operator help" "recovery_help"
    report_status "recovery help operator pass" "recovery_help_operator_pass_host"
    report_status "recovery help no-launch" "recovery_help_operator_pass_no_launch"
    report_status "recovery help checklist" "recovery_help_operator_checklist"
    report_status "recovery help pass artifact" "recovery_help_operator_pass_artifact"
    report_status "recovery help pass external" "recovery_help_operator_pass_external"
    report_status "recovery help report required" "recovery_help_pass_report_required"
    report_status "recovery help report after apply" "recovery_help_pass_report_after_apply"
    report_status "qemu pass no-launch" "qemu_visible_operator_pass_no_launch"
    report_status "qemu pass launch gate" "qemu_visible_operator_pass_launch_required"
    report_status "qemu pass stop rule" "qemu_visible_operator_pass_stop_rule"
    report_status "qemu pass confirm cmd" "qemu_visible_operator_pass_confirmed_command"
    report_status "qemu pass evidence flow" "qemu_visible_operator_pass_evidence_flow"
    report_status "qemu pass hash gate" "qemu_visible_operator_pass_capture_hash_gate"
    report_status "qemu pass hash status" "qemu_visible_operator_pass_capture_hash_status"
    report_status "qemu pass hash rejection" "qemu_visible_operator_pass_missing_capture_hash_rejected"
    report_status "qemu pass runbook report gate" "qemu_visible_operator_pass_manual_runbook_pass_report_required"
    report_status "qemu pass preflight hash" "qemu_visible_operator_pass_preflight_source"
    report_status "qemu pass preflight time" "qemu_visible_operator_pass_preflight_mtime"
    report_status "operator transcript" "operator_transcript"
    report_status "graphics enable gate" "graphics_enable_gate"
    report_status "graphics allow dry-run" "graphics_enable_gate_positive"
    report_status "graphics launch candidate" "graphics_launch_candidate"
    report_status "graphics rollback drill" "graphics_rollback_drill"
    report_status "graphics startup preflight" "graphics_startup_preflight"
    report_status "graphics startup rehearsal" "graphics_startup_rehearsal"
    report_status "graphics qemu display gate" "graphics_qemu_display_gate"
    report_status "graphics visible qemu attempt" "graphics_visible_qemu_attempt"
    report_status "graphics visible attempt transcript" "graphics_visible_attempt_transcript"
    report_status "graphics visible attempt result" "graphics_visible_attempt_result"
    report_status "graphics visible attempt runner" "graphics_visible_attempt_runner"
    report_status "graphics qemu visible boot check" "graphics_qemu_visible_boot_check"
    report_status "graphics fbdev presenter" "graphics_fbdev_present"
    report_status "rootfs DRM device probe" "graphics_drm_rootfs_probe"
    report_status "QEMU DRM device probe" "graphics_drm_qemu_probe"
    report_status "QEMU DRM card0" "graphics_drm_qemu_device"
    report_status "QEMU DRM connector" "graphics_drm_qemu_connector"
    report_status "QEMU DRM first mode" "graphics_drm_qemu_mode"
    report_status "DRM read-only open" "graphics_drm_read_only"
    report_status "DRM master not acquired" "graphics_drm_no_master"
    report_status "DRM modeset not activated" "graphics_drm_no_modeset"
    report_status "QEMU DRM dumb buffer" "graphics_drm_dumb_buffer"
    report_status "DRM dumb buffer mode" "graphics_drm_dumb_buffer_mode"
    report_status "DRM dumb buffer pitch" "graphics_drm_dumb_buffer_pitch"
    report_status "DRM dumb buffer bytes" "graphics_drm_dumb_buffer_bytes"
    report_status "DRM dumb buffer checksum" "graphics_drm_dumb_buffer_checksum"
    report_status "DRM dumb buffer mapped" "graphics_drm_dumb_buffer_mapped"
    report_status "DRM dumb buffer destroyed" "graphics_drm_dumb_buffer_destroyed"
    report_status "GBM scanout buffer foundation" "graphics_drm_gbm_scanout_buffer"
    report_status "GBM scanout and rendering usage" "graphics_drm_gbm_scanout_usage"
    report_status "GBM dma-buf export" "graphics_drm_gbm_dmabuf_export"
    report_status "GBM KMS ADDFB2 import" "graphics_drm_gbm_addfb2"
    report_status "GBM framebuffer cleanup" "graphics_drm_gbm_framebuffer_cleanup"
    report_status "GBM direct dma-buf scanout" "graphics_drm_gbm_direct_scanout"
    report_status "GBM direct GPU rendering" "graphics_drm_gbm_direct_rendered"
    report_status "GBM direct path without CPU copy" "graphics_drm_gbm_direct_no_cpu_copy"
    report_status "GBM direct page flip" "graphics_drm_gbm_direct_page_flip"
    report_status "GBM direct CRTC restoration" "graphics_drm_gbm_direct_crtc_restored"
    report_status "GBM direct capture" "graphics_drm_gbm_direct_capture"
    report_status "DRM framebuffer not created" "graphics_drm_dumb_buffer_no_framebuffer"
    report_status "DRM page flip not submitted" "graphics_drm_dumb_buffer_no_page_flip"
    report_status "DRM buffer recovery return" "graphics_drm_dumb_buffer_recovery_safe"
    report_status "DRM KMS presenter" "graphics_drm_kms_present"
    report_status "visible GPU system-surface KMS frame" "graphics_drm_gpu_surface"
    report_status "visible GPU system-surface capture" "graphics_drm_gpu_surface_capture"
    report_status "visible GPU system-surface PNG checksum" "graphics_drm_gpu_surface_png_checksum"
    report_status "GPU scanout bridge documented" "graphics_drm_gpu_surface_bridge"
    report_status "visible sampled client textures" "graphics_drm_gpu_surface_client_composited"
    report_status "visible client textures not live" "graphics_drm_gpu_surface_client_not_live"
    report_status "DRM KMS active frame" "graphics_drm_kms_active"
    report_status "DRM KMS framebuffer" "graphics_drm_kms_framebuffer"
    report_status "DRM KMS activated" "graphics_drm_kms_activated"
    report_status "DRM KMS no page flip" "graphics_drm_kms_no_page_flip"
    report_status "DRM KMS CRTC restored" "graphics_drm_kms_crtc_restored"
    report_status "DRM KMS framebuffer destroyed" "graphics_drm_kms_framebuffer_destroyed"
    report_status "DRM KMS recovery return" "graphics_drm_kms_recovery_safe"
    report_status "DRM KMS capture" "graphics_drm_kms_capture"
    report_status "DRM KMS capture size" "graphics_drm_kms_capture_dimensions"
    report_status "DRM KMS PPM checksum" "graphics_drm_kms_ppm_checksum"
    report_status "DRM KMS PNG checksum" "graphics_drm_kms_png_checksum"
    report_status "DRM page flip" "graphics_drm_page_flip"
    report_status "DRM page flip active" "graphics_drm_page_flip_active"
    report_status "DRM page flip submitted" "graphics_drm_page_flip_submitted"
    report_status "DRM page flip event" "graphics_drm_page_flip_event"
    report_status "DRM page flip front cleanup" "graphics_drm_page_flip_front_destroyed"
    report_status "DRM page flip back cleanup" "graphics_drm_page_flip_back_destroyed"
    report_status "DRM page flip CRTC restored" "graphics_drm_page_flip_crtc_restored"
    report_status "DRM page flip recovery" "graphics_drm_page_flip_recovery_safe"
    report_status "DRM page flip capture" "graphics_drm_page_flip_capture"
    report_status "DRM page flip capture size" "graphics_drm_page_flip_capture_dimensions"
    report_status "DRM page flip PPM checksum" "graphics_drm_page_flip_ppm_checksum"
    report_status "DRM page flip PNG checksum" "graphics_drm_page_flip_png_checksum"
    report_status "DRM frame loop" "graphics_drm_frame_loop"
    report_status "DRM frame loop active" "graphics_drm_frame_loop_active"
    report_status "DRM frame loop submitted" "graphics_drm_frame_loop_submitted"
    report_status "DRM frame loop received" "graphics_drm_frame_loop_received"
    report_status "DRM frame loop ordering" "graphics_drm_frame_loop_order"
    report_status "DRM frame loop alternation" "graphics_drm_frame_loop_alternation"
    report_status "DRM frame loop CRTC restored" "graphics_drm_frame_loop_crtc_restored"
    report_status "DRM frame loop recovery" "graphics_drm_frame_loop_recovery_safe"
    report_status "DRM frame loop capture" "graphics_drm_frame_loop_capture"
    report_status "DRM frame loop capture size" "graphics_drm_frame_loop_capture_dimensions"
    report_status "DRM frame loop PPM checksum" "graphics_drm_frame_loop_ppm_checksum"
    report_status "DRM frame loop PNG checksum" "graphics_drm_frame_loop_png_checksum"
    report_status "DRM session loop" "graphics_drm_session_loop"
    report_status "DRM session loop active" "graphics_drm_session_loop_active"
    report_status "DRM session owner" "graphics_drm_session_loop_owner"
    report_status "DRM session calloop" "graphics_drm_session_loop_calloop"
    report_status "DRM source owned" "graphics_drm_session_loop_source_owned"
    report_status "DRM calloop dispatch" "graphics_drm_session_loop_dispatch"
    report_status "DRM source released" "graphics_drm_session_loop_source_released"
    report_status "DRM session Wayland stopped" "graphics_drm_session_loop_wayland_stopped"
    report_status "DRM session recovery" "graphics_drm_session_loop_recovery_safe"
    report_status "DRM session capture" "graphics_drm_session_loop_capture"
    report_status "DRM session capture size" "graphics_drm_session_loop_capture_dimensions"
    report_status "DRM session PPM checksum" "graphics_drm_session_loop_ppm_checksum"
    report_status "DRM session PNG checksum" "graphics_drm_session_loop_png_checksum"
    report_status "DRM Wayland session" "graphics_drm_wayland_session"
    report_status "DRM Wayland active" "graphics_drm_wayland_session_active"
    report_status "DRM Wayland live GPU composition" "graphics_drm_wayland_gpu_composition"
    report_status "DRM Wayland virtio scanout compatibility" "graphics_drm_wayland_virtio_scanout_compat"
    report_status "DRM Wayland CPU scanout copy" "graphics_drm_wayland_cpu_scanout_copy"
    report_status "DRM Wayland GBM cleanup" "graphics_drm_wayland_gbm_cleanup"
    report_status "DRM Wayland frame readback" "graphics_drm_wayland_frame_readback"
    report_status "DRM Wayland frame checksum" "graphics_drm_wayland_frame_checksum"
    report_status "live wl_shm GPU texture upload" "graphics_drm_wayland_gpu_live_uploaded"
    report_status "live wl_shm GPU texture composition" "graphics_drm_wayland_gpu_live_composited"
    report_status "session-owned GPU context" "graphics_drm_wayland_gpu_session_context"
    report_status "live GPU repaint" "graphics_drm_wayland_gpu_repaint"
    report_status "GPU context reused" "graphics_drm_wayland_gpu_context_reused"
    report_status "Files GPU repaint" "graphics_drm_wayland_gpu_files_repaint"
    report_status "Settings GPU repaint" "graphics_drm_wayland_gpu_settings_repaint"
    report_status "client cleanup GPU repaint" "graphics_drm_wayland_gpu_cleanup_repaint"
    report_status "empty desktop GPU repaint" "graphics_drm_wayland_gpu_close_repaint"
    report_status "full session GPU repaint route" "graphics_drm_wayland_gpu_full_repaint_route"
    report_status "shared session lifecycle" "graphics_drm_wayland_shared_lifecycle"
    report_status "Wayland display created" "graphics_drm_wayland_display"
    report_status "Wayland socket bound" "graphics_drm_wayland_socket"
    report_status "Wayland client inserted" "graphics_drm_wayland_client"
    report_status "Wayland dispatch" "graphics_drm_wayland_dispatch"
    report_status "Wayland flush" "graphics_drm_wayland_flush"
    report_status "shared DRM dispatch" "graphics_drm_wayland_drm_dispatch"
    report_status "Smithay protocol globals" "graphics_drm_wayland_smithay_globals"
    report_status "Smithay compositor global" "graphics_drm_wayland_compositor_global"
    report_status "Smithay shm global" "graphics_drm_wayland_shm_global"
    report_status "Smithay xdg-shell global" "graphics_drm_wayland_xdg_shell_global"
    report_status "Aqua Seat in DRM session" "graphics_drm_wayland_seat"
    report_status "Wayland socket cleanup" "graphics_drm_wayland_socket_cleaned"
    report_status "DRM Wayland recovery" "graphics_drm_wayland_recovery_safe"
    report_status "graphical supervisor QEMU" "graphics_session_supervisor_qemu"
    report_status "supervisor bounded restarts" "graphics_session_supervisor_qemu_restarts"
    report_status "supervisor recovery fallback" "graphics_session_supervisor_qemu_recovery"
    report_status "graphical stop QEMU" "graphics_stop_qemu"
    report_status "graphical stop KMS restore" "graphics_stop_qemu_kms"
    report_status "graphical stop PID cleanup" "graphics_stop_qemu_pid"
    report_status "libinput udev source" "graphics_drm_wayland_input_source"
    report_status "libinput discovery" "graphics_drm_wayland_input_discovery"
    report_status "libinput keyboard" "graphics_drm_wayland_input_keyboard"
    report_status "selective key forwarding" "graphics_drm_wayland_input_selective_forward"
    report_status "pointer surface hit-test" "graphics_drm_wayland_input_pointer_hit_test"
    report_status "libinput pointer" "graphics_drm_wayland_input_pointer_motion"
    report_status "libinput button" "graphics_drm_wayland_input_pointer_button"
    report_status "libinput launcher" "graphics_drm_wayland_input_launcher"
    report_status "libinput dispatch" "graphics_drm_wayland_input_dispatch"
    report_status "external Wayland client" "graphics_drm_wayland_external_client"
    report_status "external client buffer" "graphics_drm_wayland_external_client_buffer"
    report_status "external client composited" "graphics_drm_wayland_external_client_composited"
    report_status "external client frame callback" "graphics_drm_wayland_external_client_frame_callback"
    report_status "external client damage" "graphics_drm_wayland_external_client_damage"
    report_status "external client focus" "graphics_drm_wayland_external_client_focus"
    report_status "QEMU evdev Aqua Seat" "graphics_evdev_aqua_seat"
    report_status "QEMU evdev keyboard" "graphics_evdev_keyboard"
    report_status "QEMU evdev pointer motion" "graphics_evdev_pointer_motion"
    report_status "QEMU evdev pointer button" "graphics_evdev_pointer_button"
    report_status "QEMU evdev launcher toggle" "graphics_evdev_launcher"
    report_status "DRM Wayland capture" "graphics_drm_wayland_capture"
    report_status "DRM Wayland capture size" "graphics_drm_wayland_capture_dimensions"
    report_status "DRM Wayland PPM checksum" "graphics_drm_wayland_ppm_checksum"
    report_status "DRM Wayland PNG checksum" "graphics_drm_wayland_png_checksum"
    report_status "headless QEMU fbdev write" "graphics_fbdev_headless_qemu_write"
    report_status "headless QEMU fbdev checksum" "graphics_fbdev_headless_qemu_checksum"
    report_status "headless QEMU runtime wallpaper" "graphics_fbdev_headless_qemu_wallpaper"
    report_status "headless QEMU fbdev mode" "graphics_fbdev_headless_qemu_mode"
    report_status "headless QEMU recovery return" "graphics_fbdev_headless_qemu_recovery_safe"
    report_status "headless QEMU screenshot" "graphics_fbdev_headless_qemu_capture"
    report_status "headless QEMU screenshot size" "graphics_fbdev_headless_qemu_capture_dimensions"
    report_status "headless QEMU PPM checksum" "graphics_fbdev_headless_qemu_ppm_checksum"
    report_status "headless QEMU PNG checksum" "graphics_fbdev_headless_qemu_png_checksum"
    report_status "headless capture unobserved" "graphics_fbdev_headless_qemu_capture_unobserved"
    report_status "graphics qemu observation marker" "graphics_qemu_observation_marker"
    report_status "qemu visible evidence record" "qemu_visible_evidence_record"
    report_status "graphics qemu observation positive" "graphics_qemu_observation_positive"
    report_status "qemu visible pass report" "qemu_visible_pass_report"
    report_status "qemu pass report evidence" "qemu_visible_pass_report_evidence_recorded"
    report_status "qemu visible manual runbook" "qemu_visible_manual_runbook"
    report_status "qemu runbook pass report required" "qemu_visible_manual_runbook_pass_report_required"
    report_status "qemu visible ready capture flow" "qemu_visible_manual_runbook_ready_capture_flow"
    report_status "qemu visible bundle apply" "qemu_visible_evidence_bundle_apply"
    report_status "qemu bundle hash verified" "qemu_visible_evidence_bundle_apply_capture_hash_verified"
    report_status "qemu visible bundle positive" "qemu_visible_evidence_bundle_apply_positive"
    report_status "qemu positive hash verified" "qemu_visible_evidence_bundle_apply_positive_capture_hash_verified"
    report_status "qemu visible bundle rejected" "qemu_visible_evidence_bundle_apply_missing_preflight_rejected"
    report_status "qemu hash bundle rejected" "qemu_visible_evidence_bundle_apply_missing_capture_hash_rejected"
    report_status "client window model" "client_window_model"
    report_status "client surface lifecycle" "client_surface_lifecycle"
    report_status "client surface registry" "client_surface_registry"
    report_status "renderer surface sources" "renderer_surface_sources"
    report_status "renderer GPU runtime" "renderer_gpu_runtime"
    report_status "renderer GPU backend" "renderer_gpu_backend_selected"
    report_status "renderer GPU no context" "renderer_gpu_no_context"
    report_status "renderer GPU offscreen frame" "renderer_gpu_offscreen_frame"
    report_status "renderer GPU context" "renderer_gpu_context_created"
    report_status "renderer GPU frame sync" "renderer_gpu_frame_synchronized"
    report_status "renderer GPU scene" "renderer_gpu_scene_surfaces"
    report_status "renderer GPU surface layers" "renderer_gpu_scene_surface_layers"
    report_status "renderer GPU system-surface shader" "renderer_gpu_surface_shader_compiled"
    report_status "renderer GPU bounded refraction" "renderer_gpu_surface_bounded"
    report_status "renderer GPU rounded surface mask" "renderer_gpu_surface_rounded_mask"
    report_status "renderer GPU surface edge light" "renderer_gpu_surface_edge_light"
    report_status "renderer GPU two-pass surface blur" "renderer_gpu_surface_blur_passes"
    report_status "renderer GPU surface blur composited" "renderer_gpu_surface_blur_composited"
    report_status "renderer GPU wallpaper" "renderer_gpu_wallpaper_composited"
    report_status "renderer sampled client texture upload" "renderer_gpu_client_textures_uploaded"
    report_status "renderer sampled client texture composition" "renderer_gpu_client_textures_composited"
    report_status "renderer client texture source not live" "renderer_gpu_client_not_live"
    report_status "renderer GPU readback" "renderer_gpu_frame_readback"
    report_status "renderer GPU deterministic" "renderer_gpu_frame_deterministic"
    report_status "renderer GPU recovery" "renderer_gpu_offscreen_recovery_safe"
    report_status "client layer pipeline" "client_layer_pipeline"
    report_status "xdg shell binding" "xdg_shell_binding"
    report_status "xdg toplevel client" "xdg_toplevel_client"
    report_status "xdg toplevel window model" "xdg_toplevel_window_model"
    report_status "scene contract" "scene_contract"
    report_status "render plan" "render_plan"
    report_status "paint plan" "paint_plan"
    report_status "frame plan" "frame_plan"
    report_status "frame buffer" "frame_buffer"
    report_status "raster" "raster"
    report_status "surface primitives" "surface_primitives"
    report_status "raster export" "raster_export"
    report_status "raster png export" "raster_png_export"
    report_status "desktop shell" "desktop_shell"

    echo
    echo "Aqua Linux graphical session cycle"
    report_status "persistent boot session" "graphics_boot_qemu_persistent"
    report_status "desktop event loop" "graphics_boot_qemu_desktop_event_loop"
    report_status "diagnostic fixtures absent" "graphics_boot_qemu_fixture_free"
    report_status "launcher runtime request" "graphics_desktop_runtime_launch_qemu"
    report_status "Aqua Files Wayland surface" "graphics_desktop_runtime_launch_files"
    report_status "runtime GPU repaint" "graphics_desktop_runtime_launch_repaint"
    report_status "Aqua Settings runtime surface" "graphics_desktop_runtime_settings"
    report_status "audio adapter QEMU safe default" "audio_adapter_qemu_safe_default"
    report_status "client damage repaint" "graphics_desktop_runtime_damage"
    report_status "normal application close" "graphics_desktop_runtime_close"
    report_status "unexpected application exit" "graphics_desktop_runtime_unexpected_exit"
    report_status "runtime process cleanup" "graphics_desktop_runtime_cleanup"
    report_status "confirmed recovery session action" "graphics_desktop_session_menu"
    report_status "session menu GPU content" "graphics_desktop_session_menu_overlay"
    report_status "second session restart" "graphics_restart_qemu"
    report_status "two start-stop cycles" "graphics_session_cycle_qemu"
    report_status "cycle socket cleanup" "graphics_session_cycle_qemu_sockets"
    report_status "cycle PID cleanup" "graphics_session_cycle_qemu_pids"
    report_status "cycle client cleanup" "graphics_session_cycle_qemu_clients"
    report_status "cycle DRM cleanup" "graphics_session_cycle_qemu_drm"

    echo
    echo "Aqua Linux boot marker summary"
    report_status "fbdev device" "fbdev_device"
    report_status "session config" "session_config"
    report_status "session runtime" "session_runtime"
    report_status "session env" "session_env"
    report_status "compositor status" "compositor_status"
    report_status "session bootstrap" "session_bootstrap"
    report_status "compositor assets" "compositor_assets"
    report_status "output plan" "output_plan"
    report_status "visible preview plan" "visible_preview_plan"
    report_status "scene contract" "scene_contract"
    report_status "render plan" "render_plan"
    report_status "paint plan" "paint_plan"
    report_status "frame plan" "frame_plan"
    report_status "frame buffer" "frame_buffer"
    report_status "raster" "raster"
    report_status "surface primitives" "surface_primitives"
    report_status "raster export" "raster_export"
    report_status "raster png export" "raster_png_export"
    report_status "session check" "session_check"
    report_status "recovery ready" "recovery_ready"

    echo
    echo "Aqua Linux boot summary contract"
    report_status "summary status" "boot_summary_status"
    report_status "summary fbdev device" "fbdev_device"
    report_status "summary session config" "session_config"
    report_status "summary session env" "session_env"
    report_status "summary output plan" "output_plan"
    report_status "summary visible preview" "visible_preview_plan"
    report_status "summary paint plan" "paint_plan"
    report_status "summary frame plan" "frame_plan"
    report_status "summary frame buffer" "frame_buffer"
    report_status "summary raster" "raster"
    report_status "summary surface primitives" "surface_primitives"
    report_status "summary raster export" "raster_export"
    report_status "summary raster png export" "raster_png_export"
    report_status "summary session check" "session_check"
    report_status "summary recovery ready" "recovery_ready"
fi
